/*
 * This file is generated by jOOQ.
 */
package com.veritynow.core.store.persistence.jooq.routines;


import com.veritynow.core.store.persistence.jooq.Public;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VnLockInodeAncestorsNowait extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter
     * <code>public.vn_lock_inode_ancestors_nowait.p_inode_id</code>.
     */
    public static final Parameter<Long> P_INODE_ID = Internal.createParameter("p_inode_id", SQLDataType.BIGINT, false, false);

    /**
     * Create a new routine call instance
     */
    public VnLockInodeAncestorsNowait() {
        super("vn_lock_inode_ancestors_nowait", Public.PUBLIC, DSL.comment(""));

        addInParameter(P_INODE_ID);
    }

    /**
     * Set the <code>p_inode_id</code> parameter IN value to the routine
     */
    public void setPInodeId(Long value) {
        setValue(P_INODE_ID, value);
    }
}
