/*
 * This file is generated by jOOQ.
 */
package com.veritynow.core.store.persistence.jooq;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import com.veritynow.core.store.persistence.jooq.tables.VnDirEntry;
import com.veritynow.core.store.persistence.jooq.tables.VnInode;
import com.veritynow.core.store.persistence.jooq.tables.VnInodePathSegment;
import com.veritynow.core.store.persistence.jooq.tables.VnLockGroup;
import com.veritynow.core.store.persistence.jooq.tables.VnNodeVersion;
import com.veritynow.core.store.persistence.jooq.tables.VnPathLock;
import com.veritynow.core.store.persistence.jooq.tables.VnTxnEpoch;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IX_DIR_CHILD = Internal.createIndex(DSL.name("ix_dir_child"), VnDirEntry.VN_DIR_ENTRY, new OrderField[] { VnDirEntry.VN_DIR_ENTRY.CHILD_ID }, false);
    public static final Index IX_DIR_PARENT = Internal.createIndex(DSL.name("ix_dir_parent"), VnDirEntry.VN_DIR_ENTRY, new OrderField[] { VnDirEntry.VN_DIR_ENTRY.PARENT_ID }, false);
    public static final Index IX_INODE_PATH_INODE = Internal.createIndex(DSL.name("ix_inode_path_inode"), VnInodePathSegment.VN_INODE_PATH_SEGMENT, new OrderField[] { VnInodePathSegment.VN_INODE_PATH_SEGMENT.INODE_ID }, false);
    public static final Index IX_VER_INODE_TIMESTAMP = Internal.createIndex(DSL.name("ix_ver_inode_timestamp"), VnNodeVersion.VN_NODE_VERSION, new OrderField[] { VnNodeVersion.VN_NODE_VERSION.INODE_ID, VnNodeVersion.VN_NODE_VERSION.TIMESTAMP.desc(), VnNodeVersion.VN_NODE_VERSION.ID.desc() }, false);
    public static final Index IX_VN_LOCK_GROUP_ACTIVE_EXPIRES = Internal.createIndex(DSL.name("ix_vn_lock_group_active_expires"), VnLockGroup.VN_LOCK_GROUP, new OrderField[] { VnLockGroup.VN_LOCK_GROUP.ACTIVE, VnLockGroup.VN_LOCK_GROUP.EXPIRES_AT }, false);
    public static final Index IX_VN_LOCK_GROUP_OWNER_ACTIVE = Internal.createIndex(DSL.name("ix_vn_lock_group_owner_active"), VnLockGroup.VN_LOCK_GROUP, new OrderField[] { VnLockGroup.VN_LOCK_GROUP.OWNER_ID, VnLockGroup.VN_LOCK_GROUP.ACTIVE }, false);
    public static final Index IX_VN_PATH_LOCK_GROUP = Internal.createIndex(DSL.name("ix_vn_path_lock_group"), VnPathLock.VN_PATH_LOCK, new OrderField[] { VnPathLock.VN_PATH_LOCK.LOCK_GROUP_ID }, false);
    public static final Index IX_VN_PATH_LOCK_OWNER_ACTIVE = Internal.createIndex(DSL.name("ix_vn_path_lock_owner_active"), VnPathLock.VN_PATH_LOCK, new OrderField[] { VnPathLock.VN_PATH_LOCK.OWNER_ID, VnPathLock.VN_PATH_LOCK.ACTIVE }, false);
    public static final Index IX_VN_PATH_LOCK_SCOPE_KEY_GIST = Internal.createIndex(DSL.name("ix_vn_path_lock_scope_key_gist"), VnPathLock.VN_PATH_LOCK, new OrderField[] { VnPathLock.VN_PATH_LOCK.SCOPE_KEY }, false);
    public static final Index IX_VN_TXN_EPOCH_STATUS = Internal.createIndex(DSL.name("ix_vn_txn_epoch_status"), VnTxnEpoch.VN_TXN_EPOCH, new OrderField[] { VnTxnEpoch.VN_TXN_EPOCH.STATUS }, false);
    public static final Index UQ_VN_INODE_SCOPE_KEY = Internal.createIndex(DSL.name("uq_vn_inode_scope_key"), VnInode.VN_INODE, new OrderField[] { VnInode.VN_INODE.SCOPE_KEY }, true);
}
