/*
 * This file is generated by jOOQ.
 */
package com.veritynow.core.store.persistence.jooq;


import com.veritynow.core.store.persistence.jooq.tables.VnDirEntry;
import com.veritynow.core.store.persistence.jooq.tables.VnInode;
import com.veritynow.core.store.persistence.jooq.tables.VnInodePathSegment;
import com.veritynow.core.store.persistence.jooq.tables.VnNodeVersion;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IX_DIR_CHILD = Internal.createIndex(DSL.name("ix_dir_child"), VnDirEntry.VN_DIR_ENTRY, new OrderField[] { VnDirEntry.VN_DIR_ENTRY.CHILD_ID }, false);
    public static final Index IX_DIR_PARENT = Internal.createIndex(DSL.name("ix_dir_parent"), VnDirEntry.VN_DIR_ENTRY, new OrderField[] { VnDirEntry.VN_DIR_ENTRY.PARENT_ID }, false);
    public static final Index IX_INODE_PATH_DIR_ENTRY = Internal.createIndex(DSL.name("ix_inode_path_dir_entry"), VnInodePathSegment.VN_INODE_PATH_SEGMENT, new OrderField[] { VnInodePathSegment.VN_INODE_PATH_SEGMENT.DIR_ENTRY_ID }, false);
    public static final Index IX_INODE_PATH_INODE = Internal.createIndex(DSL.name("ix_inode_path_inode"), VnInodePathSegment.VN_INODE_PATH_SEGMENT, new OrderField[] { VnInodePathSegment.VN_INODE_PATH_SEGMENT.INODE_ID }, false);
    public static final Index IX_VER_CORRELATION = Internal.createIndex(DSL.name("ix_ver_correlation"), VnNodeVersion.VN_NODE_VERSION, new OrderField[] { VnNodeVersion.VN_NODE_VERSION.CORRELATION_ID, VnNodeVersion.VN_NODE_VERSION.ID }, false);
    public static final Index IX_VER_HASH_ALG = Internal.createIndex(DSL.name("ix_ver_hash_alg"), VnNodeVersion.VN_NODE_VERSION, new OrderField[] { VnNodeVersion.VN_NODE_VERSION.HASH, VnNodeVersion.VN_NODE_VERSION.HASH_ALGORITHM }, false);
    public static final Index IX_VER_INODE_TIMESTAMP = Internal.createIndex(DSL.name("ix_ver_inode_timestamp"), VnNodeVersion.VN_NODE_VERSION, new OrderField[] { VnNodeVersion.VN_NODE_VERSION.INODE_ID, VnNodeVersion.VN_NODE_VERSION.TIMESTAMP.desc(), VnNodeVersion.VN_NODE_VERSION.ID.desc() }, false);
    public static final Index IX_VER_TXN_INODE = Internal.createIndex(DSL.name("ix_ver_txn_inode"), VnNodeVersion.VN_NODE_VERSION, new OrderField[] { VnNodeVersion.VN_NODE_VERSION.TRANSACTION_ID, VnNodeVersion.VN_NODE_VERSION.INODE_ID, VnNodeVersion.VN_NODE_VERSION.ID }, false);
    public static final Index IX_VER_TXN_RESULT = Internal.createIndex(DSL.name("ix_ver_txn_result"), VnNodeVersion.VN_NODE_VERSION, new OrderField[] { VnNodeVersion.VN_NODE_VERSION.TRANSACTION_ID, VnNodeVersion.VN_NODE_VERSION.TRANSACTION_RESULT, VnNodeVersion.VN_NODE_VERSION.ID }, false);
    public static final Index IX_VER_WORKFLOW = Internal.createIndex(DSL.name("ix_ver_workflow"), VnNodeVersion.VN_NODE_VERSION, new OrderField[] { VnNodeVersion.VN_NODE_VERSION.WORKFLOW_ID, VnNodeVersion.VN_NODE_VERSION.ID }, false);
    public static final Index IX_VN_INODE_SCOPE_KEY_GIST = Internal.createIndex(DSL.name("ix_vn_inode_scope_key_gist"), VnInode.VN_INODE, new OrderField[] { VnInode.VN_INODE.SCOPE_KEY }, false);
}
