/*
 * This file is generated by jOOQ.
 */
package com.veritynow.core.store.persistence.jooq;


import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import com.veritynow.core.store.persistence.jooq.tables.VnDirEntry;
import com.veritynow.core.store.persistence.jooq.tables.VnInode;
import com.veritynow.core.store.persistence.jooq.tables.VnInodePathSegment;
import com.veritynow.core.store.persistence.jooq.tables.VnLockGroup;
import com.veritynow.core.store.persistence.jooq.tables.VnNodeHead;
import com.veritynow.core.store.persistence.jooq.tables.VnNodeVersion;
import com.veritynow.core.store.persistence.jooq.tables.VnPathLock;
import com.veritynow.core.store.persistence.jooq.tables.VnTxnEpoch;
import com.veritynow.core.store.persistence.jooq.tables.records.VnDirEntryRecord;
import com.veritynow.core.store.persistence.jooq.tables.records.VnInodePathSegmentRecord;
import com.veritynow.core.store.persistence.jooq.tables.records.VnInodeRecord;
import com.veritynow.core.store.persistence.jooq.tables.records.VnLockGroupRecord;
import com.veritynow.core.store.persistence.jooq.tables.records.VnNodeHeadRecord;
import com.veritynow.core.store.persistence.jooq.tables.records.VnNodeVersionRecord;
import com.veritynow.core.store.persistence.jooq.tables.records.VnPathLockRecord;
import com.veritynow.core.store.persistence.jooq.tables.records.VnTxnEpochRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<VnDirEntryRecord> UQ_DIR_PARENT_NAME = Internal.createUniqueKey(VnDirEntry.VN_DIR_ENTRY, DSL.name("uq_dir_parent_name"), new TableField[] { VnDirEntry.VN_DIR_ENTRY.PARENT_ID, VnDirEntry.VN_DIR_ENTRY.NAME }, true);
    public static final UniqueKey<VnDirEntryRecord> VN_DIR_ENTRY_PKEY = Internal.createUniqueKey(VnDirEntry.VN_DIR_ENTRY, DSL.name("vn_dir_entry_pkey"), new TableField[] { VnDirEntry.VN_DIR_ENTRY.ID }, true);
    public static final UniqueKey<VnInodeRecord> VN_INODE_PKEY = Internal.createUniqueKey(VnInode.VN_INODE, DSL.name("vn_inode_pkey"), new TableField[] { VnInode.VN_INODE.ID }, true);
    public static final UniqueKey<VnInodePathSegmentRecord> UQ_INODE_ORD = Internal.createUniqueKey(VnInodePathSegment.VN_INODE_PATH_SEGMENT, DSL.name("uq_inode_ord"), new TableField[] { VnInodePathSegment.VN_INODE_PATH_SEGMENT.INODE_ID, VnInodePathSegment.VN_INODE_PATH_SEGMENT.ORD }, true);
    public static final UniqueKey<VnInodePathSegmentRecord> VN_INODE_PATH_SEGMENT_PKEY = Internal.createUniqueKey(VnInodePathSegment.VN_INODE_PATH_SEGMENT, DSL.name("vn_inode_path_segment_pkey"), new TableField[] { VnInodePathSegment.VN_INODE_PATH_SEGMENT.ID }, true);
    public static final UniqueKey<VnLockGroupRecord> VN_LOCK_GROUP_PKEY = Internal.createUniqueKey(VnLockGroup.VN_LOCK_GROUP, DSL.name("vn_lock_group_pkey"), new TableField[] { VnLockGroup.VN_LOCK_GROUP.LOCK_GROUP_ID }, true);
    public static final UniqueKey<VnNodeHeadRecord> VN_NODE_HEAD_PKEY = Internal.createUniqueKey(VnNodeHead.VN_NODE_HEAD, DSL.name("vn_node_head_pkey"), new TableField[] { VnNodeHead.VN_NODE_HEAD.INODE_ID }, true);
    public static final UniqueKey<VnNodeVersionRecord> VN_NODE_VERSION_PKEY = Internal.createUniqueKey(VnNodeVersion.VN_NODE_VERSION, DSL.name("vn_node_version_pkey"), new TableField[] { VnNodeVersion.VN_NODE_VERSION.ID }, true);
    public static final UniqueKey<VnPathLockRecord> VN_PATH_LOCK_PKEY = Internal.createUniqueKey(VnPathLock.VN_PATH_LOCK, DSL.name("vn_path_lock_pkey"), new TableField[] { VnPathLock.VN_PATH_LOCK.ID }, true);
    public static final UniqueKey<VnTxnEpochRecord> VN_TXN_EPOCH_PKEY = Internal.createUniqueKey(VnTxnEpoch.VN_TXN_EPOCH, DSL.name("vn_txn_epoch_pkey"), new TableField[] { VnTxnEpoch.VN_TXN_EPOCH.TXN_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<VnDirEntryRecord, VnInodeRecord> VN_DIR_ENTRY__FKPHTN4ICDTOH8XGJUVTW4QCD0I = Internal.createForeignKey(VnDirEntry.VN_DIR_ENTRY, DSL.name("fkphtn4icdtoh8xgjuvtw4qcd0i"), new TableField[] { VnDirEntry.VN_DIR_ENTRY.CHILD_ID }, Keys.VN_INODE_PKEY, new TableField[] { VnInode.VN_INODE.ID }, true);
    public static final ForeignKey<VnDirEntryRecord, VnInodeRecord> VN_DIR_ENTRY__FKRYI5XNY4GG8SP06UEF12IEEQ5 = Internal.createForeignKey(VnDirEntry.VN_DIR_ENTRY, DSL.name("fkryi5xny4gg8sp06uef12ieeq5"), new TableField[] { VnDirEntry.VN_DIR_ENTRY.PARENT_ID }, Keys.VN_INODE_PKEY, new TableField[] { VnInode.VN_INODE.ID }, true);
    public static final ForeignKey<VnInodePathSegmentRecord, VnDirEntryRecord> VN_INODE_PATH_SEGMENT__FKA7EHNITIJGI0LE9M875FXW42V = Internal.createForeignKey(VnInodePathSegment.VN_INODE_PATH_SEGMENT, DSL.name("fka7ehnitijgi0le9m875fxw42v"), new TableField[] { VnInodePathSegment.VN_INODE_PATH_SEGMENT.DIR_ENTRY_ID }, Keys.VN_DIR_ENTRY_PKEY, new TableField[] { VnDirEntry.VN_DIR_ENTRY.ID }, true);
    public static final ForeignKey<VnInodePathSegmentRecord, VnInodeRecord> VN_INODE_PATH_SEGMENT__FKG9TO0SPYUX7E4CYP7FPXQ27DJ = Internal.createForeignKey(VnInodePathSegment.VN_INODE_PATH_SEGMENT, DSL.name("fkg9to0spyux7e4cyp7fpxq27dj"), new TableField[] { VnInodePathSegment.VN_INODE_PATH_SEGMENT.INODE_ID }, Keys.VN_INODE_PKEY, new TableField[] { VnInode.VN_INODE.ID }, true);
    public static final ForeignKey<VnNodeHeadRecord, VnInodeRecord> VN_NODE_HEAD__FKAONO5M08T5X8TXQ0VG3CA3WDH = Internal.createForeignKey(VnNodeHead.VN_NODE_HEAD, DSL.name("fkaono5m08t5x8txq0vg3ca3wdh"), new TableField[] { VnNodeHead.VN_NODE_HEAD.INODE_ID }, Keys.VN_INODE_PKEY, new TableField[] { VnInode.VN_INODE.ID }, true);
    public static final ForeignKey<VnNodeHeadRecord, VnNodeVersionRecord> VN_NODE_HEAD__FKOD48YV13FHDRS5RXJXMJ8U1OD = Internal.createForeignKey(VnNodeHead.VN_NODE_HEAD, DSL.name("fkod48yv13fhdrs5rxjxmj8u1od"), new TableField[] { VnNodeHead.VN_NODE_HEAD.VERSION_ID }, Keys.VN_NODE_VERSION_PKEY, new TableField[] { VnNodeVersion.VN_NODE_VERSION.ID }, true);
    public static final ForeignKey<VnNodeVersionRecord, VnInodeRecord> VN_NODE_VERSION__FKGSEA7TLNQRYBIDBRINB952LW0 = Internal.createForeignKey(VnNodeVersion.VN_NODE_VERSION, DSL.name("fkgsea7tlnqrybidbrinb952lw0"), new TableField[] { VnNodeVersion.VN_NODE_VERSION.INODE_ID }, Keys.VN_INODE_PKEY, new TableField[] { VnInode.VN_INODE.ID }, true);
    public static final ForeignKey<VnPathLockRecord, VnLockGroupRecord> VN_PATH_LOCK__VN_PATH_LOCK_LOCK_GROUP_ID_FKEY = Internal.createForeignKey(VnPathLock.VN_PATH_LOCK, DSL.name("vn_path_lock_lock_group_id_fkey"), new TableField[] { VnPathLock.VN_PATH_LOCK.LOCK_GROUP_ID }, Keys.VN_LOCK_GROUP_PKEY, new TableField[] { VnLockGroup.VN_LOCK_GROUP.LOCK_GROUP_ID }, true);
}
