/*
 * This file is generated by jOOQ.
 */
package com.veritynow.core.store.persistence.jooq;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;

import com.veritynow.core.store.persistence.jooq.tables.VnBlob;
import com.veritynow.core.store.persistence.jooq.tables.VnDirEntry;
import com.veritynow.core.store.persistence.jooq.tables.VnInode;
import com.veritynow.core.store.persistence.jooq.tables.VnInodePathSegment;
import com.veritynow.core.store.persistence.jooq.tables.VnNodeHead;
import com.veritynow.core.store.persistence.jooq.tables.VnNodeVersion;


/**
 * standard public schema
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.vn_blob</code>.
     */
    public final VnBlob VN_BLOB = VnBlob.VN_BLOB;

    /**
     * The table <code>public.vn_dir_entry</code>.
     */
    public final VnDirEntry VN_DIR_ENTRY = VnDirEntry.VN_DIR_ENTRY;

    /**
     * The table <code>public.vn_inode</code>.
     */
    public final VnInode VN_INODE = VnInode.VN_INODE;

    /**
     * The table <code>public.vn_inode_path_segment</code>.
     */
    public final VnInodePathSegment VN_INODE_PATH_SEGMENT = VnInodePathSegment.VN_INODE_PATH_SEGMENT;

    /**
     * The table <code>public.vn_node_head</code>.
     */
    public final VnNodeHead VN_NODE_HEAD = VnNodeHead.VN_NODE_HEAD;

    /**
     * The table <code>public.vn_node_version</code>.
     */
    public final VnNodeVersion VN_NODE_VERSION = VnNodeVersion.VN_NODE_VERSION;

    /**
     * No further instances allowed
     */
    private Public() {
        super(DSL.name("public"), null, DSL.comment("standard public schema"));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            VnBlob.VN_BLOB,
            VnDirEntry.VN_DIR_ENTRY,
            VnInode.VN_INODE,
            VnInodePathSegment.VN_INODE_PATH_SEGMENT,
            VnNodeHead.VN_NODE_HEAD,
            VnNodeVersion.VN_NODE_VERSION
        );
    }
}
