/*
 * This file is generated by jOOQ.
 */
package com.veritynow.core.store.persistence.jooq;


import org.jooq.Configuration;

import com.veritynow.core.store.persistence.jooq.routines.VnLockInodeAncestorsNowait;


/**
 * Convenience access to all stored procedures and functions in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Routines {

    /**
     * Call <code>public.vn_lock_inode_ancestors_nowait</code>
     */
    public static void vnLockInodeAncestorsNowait(
          Configuration configuration
        , Long pInodeId
    ) {
        VnLockInodeAncestorsNowait p = new VnLockInodeAncestorsNowait();
        p.setPInodeId(pInodeId);

        p.execute(configuration);
    }
}
