/*
 * This file is generated by jOOQ.
 */
package com.veritynow.core.store.persistence.jooq;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Sequences {

    /**
     * The sequence <code>public.vn_fence_token_seq</code>
     */
    public static final Sequence<Long> VN_FENCE_TOKEN_SEQ = Internal.createSequence("vn_fence_token_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
