/*
 * This file is generated by jOOQ.
 */
package com.veritynow.core.store.persistence.jooq;


import com.veritynow.core.store.persistence.jooq.tables.VnBlob;
import com.veritynow.core.store.persistence.jooq.tables.VnDirEntry;
import com.veritynow.core.store.persistence.jooq.tables.VnInode;
import com.veritynow.core.store.persistence.jooq.tables.VnInodePathSegment;
import com.veritynow.core.store.persistence.jooq.tables.VnNodeHead;
import com.veritynow.core.store.persistence.jooq.tables.VnNodeVersion;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.vn_blob</code>.
     */
    public static final VnBlob VN_BLOB = VnBlob.VN_BLOB;

    /**
     * The table <code>public.vn_dir_entry</code>.
     */
    public static final VnDirEntry VN_DIR_ENTRY = VnDirEntry.VN_DIR_ENTRY;

    /**
     * The table <code>public.vn_inode</code>.
     */
    public static final VnInode VN_INODE = VnInode.VN_INODE;

    /**
     * The table <code>public.vn_inode_path_segment</code>.
     */
    public static final VnInodePathSegment VN_INODE_PATH_SEGMENT = VnInodePathSegment.VN_INODE_PATH_SEGMENT;

    /**
     * The table <code>public.vn_node_head</code>.
     */
    public static final VnNodeHead VN_NODE_HEAD = VnNodeHead.VN_NODE_HEAD;

    /**
     * The table <code>public.vn_node_version</code>.
     */
    public static final VnNodeVersion VN_NODE_VERSION = VnNodeVersion.VN_NODE_VERSION;
}
