/*
 * This file is generated by jOOQ.
 */
package com.veritynow.core.store.persistence.jooq.tables.records;


import com.veritynow.core.store.persistence.jooq.tables.VnBlob;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VnBlobRecord extends UpdatableRecordImpl<VnBlobRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.vn_blob.hash</code>.
     */
    public void setHash(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.vn_blob.hash</code>.
     */
    public String getHash() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.vn_blob.hash_algorithm</code>.
     */
    public void setHashAlgorithm(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.vn_blob.hash_algorithm</code>.
     */
    public String getHashAlgorithm() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.vn_blob.size</code>.
     */
    public void setSize(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.vn_blob.size</code>.
     */
    public Long getSize() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.vn_blob.mime_type</code>.
     */
    public void setMimeType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.vn_blob.mime_type</code>.
     */
    public String getMimeType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.vn_blob.name</code>.
     */
    public void setName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.vn_blob.name</code>.
     */
    public String getName() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VnBlobRecord
     */
    public VnBlobRecord() {
        super(VnBlob.VN_BLOB);
    }

    /**
     * Create a detached, initialised VnBlobRecord
     */
    public VnBlobRecord(String hash, String hashAlgorithm, Long size, String mimeType, String name) {
        super(VnBlob.VN_BLOB);

        setHash(hash);
        setHashAlgorithm(hashAlgorithm);
        setSize(size);
        setMimeType(mimeType);
        setName(name);
        resetTouchedOnNotNull();
    }
}
