/*
 * This file is generated by jOOQ.
 */
package com.veritynow.core.store.persistence.jooq.tables.records;


import com.veritynow.core.store.persistence.jooq.tables.VnDirEntry;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VnDirEntryRecord extends UpdatableRecordImpl<VnDirEntryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.vn_dir_entry.child_id</code>.
     */
    public void setChildId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.vn_dir_entry.child_id</code>.
     */
    public Long getChildId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.vn_dir_entry.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.vn_dir_entry.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(1);
    }

    /**
     * Setter for <code>public.vn_dir_entry.id</code>.
     */
    public void setId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.vn_dir_entry.id</code>.
     */
    public Long getId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.vn_dir_entry.parent_id</code>.
     */
    public void setParentId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.vn_dir_entry.parent_id</code>.
     */
    public Long getParentId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.vn_dir_entry.name</code>.
     */
    public void setName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.vn_dir_entry.name</code>.
     */
    public String getName() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VnDirEntryRecord
     */
    public VnDirEntryRecord() {
        super(VnDirEntry.VN_DIR_ENTRY);
    }

    /**
     * Create a detached, initialised VnDirEntryRecord
     */
    public VnDirEntryRecord(Long childId, OffsetDateTime createdAt, Long id, Long parentId, String name) {
        super(VnDirEntry.VN_DIR_ENTRY);

        setChildId(childId);
        setCreatedAt(createdAt);
        setId(id);
        setParentId(parentId);
        setName(name);
        resetTouchedOnNotNull();
    }
}
