/*
 * This file is generated by jOOQ.
 */
package com.veritynow.core.store.persistence.jooq.tables.records;


import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.postgres.extensions.types.Ltree;

import com.veritynow.core.store.persistence.jooq.tables.VnInode;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VnInodeRecord extends UpdatableRecordImpl<VnInodeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.vn_inode.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.vn_inode.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(0);
    }

    /**
     * Setter for <code>public.vn_inode.id</code>.
     */
    public void setId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.vn_inode.id</code>.
     */
    public Long getId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.vn_inode.scope_key</code>.
     */
    public void setScopeKey(Ltree value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.vn_inode.scope_key</code>.
     */
    public Ltree getScopeKey() {
        return (Ltree) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VnInodeRecord
     */
    public VnInodeRecord() {
        super(VnInode.VN_INODE);
    }

    /**
     * Create a detached, initialised VnInodeRecord
     */
    public VnInodeRecord(OffsetDateTime createdAt, Long id, Ltree scopeKey) {
        super(VnInode.VN_INODE);

        setCreatedAt(createdAt);
        setId(id);
        setScopeKey(scopeKey);
        resetChangedOnNotNull();
    }
}
