/*
 * This file is generated by jOOQ.
 */
package com.veritynow.core.store.persistence.jooq.tables.records;


import com.veritynow.core.store.persistence.jooq.tables.VnInodePathSegment;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VnInodePathSegmentRecord extends UpdatableRecordImpl<VnInodePathSegmentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.vn_inode_path_segment.ord</code>.
     */
    public void setOrd(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.vn_inode_path_segment.ord</code>.
     */
    public Integer getOrd() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.vn_inode_path_segment.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.vn_inode_path_segment.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(1);
    }

    /**
     * Setter for <code>public.vn_inode_path_segment.dir_entry_id</code>.
     */
    public void setDirEntryId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.vn_inode_path_segment.dir_entry_id</code>.
     */
    public Long getDirEntryId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.vn_inode_path_segment.id</code>.
     */
    public void setId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.vn_inode_path_segment.id</code>.
     */
    public Long getId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.vn_inode_path_segment.inode_id</code>.
     */
    public void setInodeId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.vn_inode_path_segment.inode_id</code>.
     */
    public Long getInodeId() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VnInodePathSegmentRecord
     */
    public VnInodePathSegmentRecord() {
        super(VnInodePathSegment.VN_INODE_PATH_SEGMENT);
    }

    /**
     * Create a detached, initialised VnInodePathSegmentRecord
     */
    public VnInodePathSegmentRecord(Integer ord, OffsetDateTime createdAt, Long dirEntryId, Long id, Long inodeId) {
        super(VnInodePathSegment.VN_INODE_PATH_SEGMENT);

        setOrd(ord);
        setCreatedAt(createdAt);
        setDirEntryId(dirEntryId);
        setId(id);
        setInodeId(inodeId);
        resetChangedOnNotNull();
    }
}
