/*
 * This file is generated by jOOQ.
 */
package com.veritynow.core.store.persistence.jooq.tables.records;


import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import com.veritynow.core.store.persistence.jooq.tables.VnLockGroup;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VnLockGroupRecord extends UpdatableRecordImpl<VnLockGroupRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.vn_lock_group.lock_group_id</code>.
     */
    public void setLockGroupId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.vn_lock_group.lock_group_id</code>.
     */
    public UUID getLockGroupId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.vn_lock_group.owner_id</code>.
     */
    public void setOwnerId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.vn_lock_group.owner_id</code>.
     */
    public String getOwnerId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.vn_lock_group.fence_token</code>.
     */
    public void setFenceToken(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.vn_lock_group.fence_token</code>.
     */
    public Long getFenceToken() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.vn_lock_group.active</code>.
     */
    public void setActive(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.vn_lock_group.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.vn_lock_group.acquired_at</code>.
     */
    public void setAcquiredAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.vn_lock_group.acquired_at</code>.
     */
    public OffsetDateTime getAcquiredAt() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.vn_lock_group.expires_at</code>.
     */
    public void setExpiresAt(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.vn_lock_group.expires_at</code>.
     */
    public OffsetDateTime getExpiresAt() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>public.vn_lock_group.released_at</code>.
     */
    public void setReleasedAt(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.vn_lock_group.released_at</code>.
     */
    public OffsetDateTime getReleasedAt() {
        return (OffsetDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VnLockGroupRecord
     */
    public VnLockGroupRecord() {
        super(VnLockGroup.VN_LOCK_GROUP);
    }

    /**
     * Create a detached, initialised VnLockGroupRecord
     */
    public VnLockGroupRecord(UUID lockGroupId, String ownerId, Long fenceToken, Boolean active, OffsetDateTime acquiredAt, OffsetDateTime expiresAt, OffsetDateTime releasedAt) {
        super(VnLockGroup.VN_LOCK_GROUP);

        setLockGroupId(lockGroupId);
        setOwnerId(ownerId);
        setFenceToken(fenceToken);
        setActive(active);
        setAcquiredAt(acquiredAt);
        setExpiresAt(expiresAt);
        setReleasedAt(releasedAt);
        resetChangedOnNotNull();
    }
}
