/*
 * This file is generated by jOOQ.
 */
package com.veritynow.core.store.persistence.jooq.tables.records;


import com.veritynow.core.store.persistence.jooq.tables.VnNodeHead;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VnNodeHeadRecord extends UpdatableRecordImpl<VnNodeHeadRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.vn_node_head.fence_token</code>.
     */
    public void setFenceToken(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.vn_node_head.fence_token</code>.
     */
    public Long getFenceToken() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.vn_node_head.inode_id</code>.
     */
    public void setInodeId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.vn_node_head.inode_id</code>.
     */
    public Long getInodeId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.vn_node_head.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.vn_node_head.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.vn_node_head.version_id</code>.
     */
    public void setVersionId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.vn_node_head.version_id</code>.
     */
    public Long getVersionId() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VnNodeHeadRecord
     */
    public VnNodeHeadRecord() {
        super(VnNodeHead.VN_NODE_HEAD);
    }

    /**
     * Create a detached, initialised VnNodeHeadRecord
     */
    public VnNodeHeadRecord(Long fenceToken, Long inodeId, OffsetDateTime updatedAt, Long versionId) {
        super(VnNodeHead.VN_NODE_HEAD);

        setFenceToken(fenceToken);
        setInodeId(inodeId);
        setUpdatedAt(updatedAt);
        setVersionId(versionId);
        resetTouchedOnNotNull();
    }
}
