/*
 * This file is generated by jOOQ.
 */
package com.veritynow.core.store.persistence.jooq.tables.records;


import com.veritynow.core.store.persistence.jooq.tables.VnNodeVersion;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VnNodeVersionRecord extends UpdatableRecordImpl<VnNodeVersionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.vn_node_version.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.vn_node_version.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.vn_node_version.inode_id</code>.
     */
    public void setInodeId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.vn_node_version.inode_id</code>.
     */
    public Long getInodeId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.vn_node_version.size</code>.
     */
    public void setSize(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.vn_node_version.size</code>.
     */
    public Long getSize() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.vn_node_version.timestamp</code>.
     */
    public void setTimestamp(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.vn_node_version.timestamp</code>.
     */
    public Long getTimestamp() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.vn_node_version.context_name</code>.
     */
    public void setContextName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.vn_node_version.context_name</code>.
     */
    public String getContextName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.vn_node_version.correlation_id</code>.
     */
    public void setCorrelationId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.vn_node_version.correlation_id</code>.
     */
    public String getCorrelationId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.vn_node_version.hash</code>.
     */
    public void setHash(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.vn_node_version.hash</code>.
     */
    public String getHash() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.vn_node_version.mime_type</code>.
     */
    public void setMimeType(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.vn_node_version.mime_type</code>.
     */
    public String getMimeType() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.vn_node_version.name</code>.
     */
    public void setName(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.vn_node_version.name</code>.
     */
    public String getName() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.vn_node_version.operation</code>.
     */
    public void setOperation(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.vn_node_version.operation</code>.
     */
    public String getOperation() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.vn_node_version.path</code>.
     */
    public void setPath(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.vn_node_version.path</code>.
     */
    public String getPath() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.vn_node_version.principal</code>.
     */
    public void setPrincipal(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.vn_node_version.principal</code>.
     */
    public String getPrincipal() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.vn_node_version.transaction_id</code>.
     */
    public void setTransactionId(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.vn_node_version.transaction_id</code>.
     */
    public String getTransactionId() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.vn_node_version.transaction_result</code>.
     */
    public void setTransactionResult(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.vn_node_version.transaction_result</code>.
     */
    public String getTransactionResult() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.vn_node_version.workflow_id</code>.
     */
    public void setWorkflowId(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.vn_node_version.workflow_id</code>.
     */
    public String getWorkflowId() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VnNodeVersionRecord
     */
    public VnNodeVersionRecord() {
        super(VnNodeVersion.VN_NODE_VERSION);
    }

    /**
     * Create a detached, initialised VnNodeVersionRecord
     */
    public VnNodeVersionRecord(Long id, Long inodeId, Long size, Long timestamp, String contextName, String correlationId, String hash, String mimeType, String name, String operation, String path, String principal, String transactionId, String transactionResult, String workflowId) {
        super(VnNodeVersion.VN_NODE_VERSION);

        setId(id);
        setInodeId(inodeId);
        setSize(size);
        setTimestamp(timestamp);
        setContextName(contextName);
        setCorrelationId(correlationId);
        setHash(hash);
        setMimeType(mimeType);
        setName(name);
        setOperation(operation);
        setPath(path);
        setPrincipal(principal);
        setTransactionId(transactionId);
        setTransactionResult(transactionResult);
        setWorkflowId(workflowId);
        resetChangedOnNotNull();
    }
}
