/*
 * This file is generated by jOOQ.
 */
package com.veritynow.core.store.persistence.jooq.tables.records;


import com.veritynow.core.store.jooq.LTree;
import com.veritynow.core.store.persistence.jooq.tables.VnPathLock;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VnPathLockRecord extends UpdatableRecordImpl<VnPathLockRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.vn_path_lock.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.vn_path_lock.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.vn_path_lock.lock_group_id</code>.
     */
    public void setLockGroupId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.vn_path_lock.lock_group_id</code>.
     */
    public UUID getLockGroupId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.vn_path_lock.owner_id</code>.
     */
    public void setOwnerId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.vn_path_lock.owner_id</code>.
     */
    public String getOwnerId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.vn_path_lock.scope_key</code>.
     */
    public void setScopeKey(LTree value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.vn_path_lock.scope_key</code>.
     */
    public LTree getScopeKey() {
        return (LTree) get(3);
    }

    /**
     * Setter for <code>public.vn_path_lock.active</code>.
     */
    public void setActive(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.vn_path_lock.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.vn_path_lock.acquired_at</code>.
     */
    public void setAcquiredAt(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.vn_path_lock.acquired_at</code>.
     */
    public OffsetDateTime getAcquiredAt() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>public.vn_path_lock.released_at</code>.
     */
    public void setReleasedAt(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.vn_path_lock.released_at</code>.
     */
    public OffsetDateTime getReleasedAt() {
        return (OffsetDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VnPathLockRecord
     */
    public VnPathLockRecord() {
        super(VnPathLock.VN_PATH_LOCK);
    }

    /**
     * Create a detached, initialised VnPathLockRecord
     */
    public VnPathLockRecord(Long id, UUID lockGroupId, String ownerId, LTree scopeKey, Boolean active, OffsetDateTime acquiredAt, OffsetDateTime releasedAt) {
        super(VnPathLock.VN_PATH_LOCK);

        setId(id);
        setLockGroupId(lockGroupId);
        setOwnerId(ownerId);
        setScopeKey(scopeKey);
        setActive(active);
        setAcquiredAt(acquiredAt);
        setReleasedAt(releasedAt);
        resetChangedOnNotNull();
    }
}
