/*
 * This file is generated by jOOQ.
 */
package com.veritynow.core.store.persistence.jooq.tables.records;


import com.veritynow.core.store.persistence.jooq.tables.VnTxnEpoch;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VnTxnEpochRecord extends UpdatableRecordImpl<VnTxnEpochRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.vn_txn_epoch.txn_id</code>.
     */
    public void setTxnId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.vn_txn_epoch.txn_id</code>.
     */
    public String getTxnId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.vn_txn_epoch.lock_group_id</code>.
     */
    public void setLockGroupId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.vn_txn_epoch.lock_group_id</code>.
     */
    public UUID getLockGroupId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.vn_txn_epoch.fence_token</code>.
     */
    public void setFenceToken(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.vn_txn_epoch.fence_token</code>.
     */
    public Long getFenceToken() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.vn_txn_epoch.status</code>.
     */
    public void setStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.vn_txn_epoch.status</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.vn_txn_epoch.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.vn_txn_epoch.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VnTxnEpochRecord
     */
    public VnTxnEpochRecord() {
        super(VnTxnEpoch.VN_TXN_EPOCH);
    }

    /**
     * Create a detached, initialised VnTxnEpochRecord
     */
    public VnTxnEpochRecord(String txnId, UUID lockGroupId, Long fenceToken, String status, OffsetDateTime updatedAt) {
        super(VnTxnEpoch.VN_TXN_EPOCH);

        setTxnId(txnId);
        setLockGroupId(lockGroupId);
        setFenceToken(fenceToken);
        setStatus(status);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }
}
