create schema if not exists "public";
create extension if not exists ltree;

create sequence "public"."vn_fence_token_seq";
alter table if exists "public"."vn_path_lock" drop constraint if exists "vn_path_lock_lock_group_id_fkey";
alter table if exists "public"."vn_node_version" drop constraint if exists "fkgsea7tlnqrybidbrinb952lw0";
alter table if exists "public"."vn_node_head" drop constraint if exists "fkod48yv13fhdrs5rxjxmj8u1od";
alter table if exists "public"."vn_node_head" drop constraint if exists "fkaono5m08t5x8txq0vg3ca3wdh";
alter table if exists "public"."vn_inode_path_segment" drop constraint if exists "fkg9to0spyux7e4cyp7fpxq27dj";
alter table if exists "public"."vn_inode_path_segment" drop constraint if exists "fka7ehnitijgi0le9m875fxw42v";
alter table if exists "public"."vn_dir_entry" drop constraint if exists "fkryi5xny4gg8sp06uef12ieeq5";
alter table if exists "public"."vn_dir_entry" drop constraint if exists "fkphtn4icdtoh8xgjuvtw4qcd0i";
drop index if exists "ix_vn_txn_epoch_status";
drop index if exists "ix_vn_path_lock_scope_key_gist";
drop index if exists "ix_vn_path_lock_owner_active";
drop index if exists "ix_vn_path_lock_group";
drop index if exists "ix_ver_inode_timestamp";
drop index if exists "ix_vn_lock_group_owner_active";
drop index if exists "ix_vn_lock_group_active_expires";
drop index if exists "ix_inode_path_inode";
drop index if exists "uq_vn_inode_scope_key";
drop index if exists "ix_dir_parent";
drop index if exists "ix_dir_child";
drop table if exists "public"."vn_txn_epoch";
drop table if exists "public"."vn_path_lock";
drop table if exists "public"."vn_node_version";
drop table if exists "public"."vn_node_head";
drop table if exists "public"."vn_lock_group";
drop table if exists "public"."vn_inode_path_segment";
drop table if exists "public"."vn_inode";
drop table if exists "public"."vn_dir_entry";
