create schema if not exists "public";
create extension if not exists ltree;

alter table if exists "public"."vn_blob" drop constraint if exists "vn_blob_pkey" cascade;
alter table if exists "public"."vn_dir_entry" drop constraint if exists "uq_dir_parent_name" cascade;
alter table if exists "public"."vn_dir_entry" drop constraint if exists "vn_dir_entry_pkey" cascade;
alter table if exists "public"."vn_dir_entry" drop constraint if exists "vn_dir_entry_child_id_fk" cascade;
alter table if exists "public"."vn_dir_entry" drop constraint if exists "vn_dir_entry_parent_id_fk" cascade;
alter table if exists "public"."vn_inode" drop constraint if exists "uq_vn_inode_scope_key" cascade;
alter table if exists "public"."vn_inode" drop constraint if exists "vn_inode_pkey" cascade;
alter table if exists "public"."vn_inode_path_segment" drop constraint if exists "uq_inode_ord" cascade;
alter table if exists "public"."vn_inode_path_segment" drop constraint if exists "vn_inode_path_segment_pkey" cascade;
alter table if exists "public"."vn_inode_path_segment" drop constraint if exists "vn_inode_path_segment_dir_entry_id_fk" cascade;
alter table if exists "public"."vn_inode_path_segment" drop constraint if exists "vn_inode_path_segment_inode_id_fk" cascade;
alter table if exists "public"."vn_lock_group" drop constraint if exists "vn_lock_group_pkey" cascade;
alter table if exists "public"."vn_node_head" drop constraint if exists "vn_node_head_pkey" cascade;
alter table if exists "public"."vn_node_head" drop constraint if exists "vn_node_head_inode_id_fk" cascade;
alter table if exists "public"."vn_node_head" drop constraint if exists "vn_node_head_version_id_fk" cascade;
alter table if exists "public"."vn_node_version" drop constraint if exists "vn_node_version_pkey" cascade;
alter table if exists "public"."vn_node_version" drop constraint if exists "vn_node_version_inode_id_fk" cascade;
alter table if exists "public"."vn_path_lock" drop constraint if exists "vn_path_lock_pkey" cascade;
alter table if exists "public"."vn_path_lock" drop constraint if exists "vn_path_lock_lock_group_id_fk" cascade;
alter table if exists "public"."vn_txn_epoch" drop constraint if exists "vn_txn_epoch_pkey" cascade;
drop index if exists "ix_dir_child" cascade;
drop index if exists "ix_dir_parent" cascade;
drop index if exists "ix_inode_path_inode" cascade;
drop index if exists "ix_ver_inode_timestamp" cascade;
drop index if exists "ix_vn_lock_group_active_expires" cascade;
drop index if exists "ix_vn_lock_group_owner_active" cascade;
drop index if exists "ix_vn_path_lock_group" cascade;
drop index if exists "ix_vn_path_lock_owner_active" cascade;
drop index if exists "ix_vn_path_lock_scope_key_gist" cascade;
drop index if exists "ix_vn_txn_epoch_status" cascade;
drop table if exists "public"."vn_txn_epoch" cascade;
drop table if exists "public"."vn_path_lock" cascade;
drop table if exists "public"."vn_node_version" cascade;
drop table if exists "public"."vn_node_head" cascade;
drop table if exists "public"."vn_lock_group" cascade;
drop table if exists "public"."vn_inode_path_segment" cascade;
drop table if exists "public"."vn_inode" cascade;
drop table if exists "public"."vn_dir_entry" cascade;
drop table if exists "public"."vn_blob" cascade;
drop sequence if exists "public"."vn_fence_token_seq";
