create schema if not exists "public";
create extension if not exists ltree;

create table if not exists "public"."vn_dir_entry" (
  "child_id" bigint not null,
  "created_at" timestamp(6) with time zone not null,
  "id" bigint generated by default as identity not null,
  "parent_id" bigint not null,
  "name" varchar(255) not null,
  constraint "vn_dir_entry_pkey" primary key ("id"),
  constraint "uq_dir_parent_name" unique ("parent_id", "name")
);
create table if not exists "public"."vn_inode" (
  "created_at" timestamp(6) with time zone not null,
  "id" bigint generated by default as identity not null,
  "scope_key" "public"."ltree",
  constraint "vn_inode_pkey" primary key ("id")
);
create table if not exists "public"."vn_inode_path_segment" (
  "ord" int not null,
  "created_at" timestamp(6) with time zone not null,
  "dir_entry_id" bigint not null,
  "id" bigint generated by default as identity not null,
  "inode_id" bigint not null,
  constraint "vn_inode_path_segment_pkey" primary key ("id"),
  constraint "uq_inode_ord" unique ("inode_id", "ord")
);
create table if not exists "public"."vn_lock_group" (
  "lock_group_id" uuid not null,
  "owner_id" text not null,
  "fence_token" bigint,
  "active" boolean not null default true,
  "acquired_at" timestamp(6) with time zone not null default now(),
  "expires_at" timestamp(6) with time zone,
  "released_at" timestamp(6) with time zone,
  constraint "vn_lock_group_pkey" primary key ("lock_group_id")
);
create table if not exists "public"."vn_node_head" (
  "fence_token" bigint,
  "inode_id" bigint not null,
  "updated_at" timestamp(6) with time zone not null,
  "version_id" bigint not null,
  constraint "vn_node_head_pkey" primary key ("inode_id")
);
create table if not exists "public"."vn_node_version" (
  "id" bigint generated by default as identity not null,
  "inode_id" bigint not null,
  "size" bigint not null,
  "timestamp" bigint not null,
  "context_name" varchar(255),
  "correlation_id" varchar(255),
  "hash" varchar(255),
  "mime_type" varchar(255),
  "name" varchar(255),
  "operation" varchar(255),
  "path" varchar(255),
  "principal" varchar(255),
  "transaction_id" varchar(255),
  "transaction_result" varchar(255),
  "workflow_id" varchar(255),
  constraint "vn_node_version_pkey" primary key ("id")
);
create table if not exists "public"."vn_path_lock" (
  "id" bigint generated by default as identity not null,
  "lock_group_id" uuid not null,
  "owner_id" text not null,
  "scope_key" "public"."ltree" not null,
  "active" boolean not null default true,
  "acquired_at" timestamp(6) with time zone not null default now(),
  "released_at" timestamp(6) with time zone,
  constraint "vn_path_lock_pkey" primary key ("id")
);
create table if not exists "public"."vn_txn_epoch" (
  "txn_id" text not null,
  "lock_group_id" uuid,
  "fence_token" bigint,
  "status" text not null,
  "updated_at" timestamp(6) with time zone not null default now(),
  constraint "vn_txn_epoch_pkey" primary key ("txn_id")
);
create index if not exists "ix_dir_child" on "public"."vn_dir_entry"("child_id");
create index if not exists "ix_dir_parent" on "public"."vn_dir_entry"("parent_id");
create unique index if not exists "uq_vn_inode_scope_key" on "public"."vn_inode"("scope_key");
create index if not exists "ix_inode_path_inode" on "public"."vn_inode_path_segment"("inode_id");
create index if not exists "ix_vn_lock_group_active_expires" on "public"."vn_lock_group"("active", "expires_at");
create index if not exists "ix_vn_lock_group_owner_active" on "public"."vn_lock_group"("owner_id", "active");
create index if not exists "ix_ver_inode_timestamp" on "public"."vn_node_version"("inode_id", "timestamp" desc, "id" desc);
create index if not exists "ix_vn_path_lock_group" on "public"."vn_path_lock"("lock_group_id");
create index if not exists "ix_vn_path_lock_owner_active" on "public"."vn_path_lock"("owner_id", "active");
create index if not exists "ix_vn_path_lock_scope_key_gist" on "public"."vn_path_lock"("scope_key");
create index if not exists "ix_vn_txn_epoch_status" on "public"."vn_txn_epoch"("status");

alter table if exists "public"."vn_dir_entry" drop constraint if exists "fkphtn4icdtoh8xgjuvtw4qcd0i",
	add constraint  "fkphtn4icdtoh8xgjuvtw4qcd0i"  foreign key ("child_id") references "public"."vn_inode" ("id");
	
alter table if exists "public"."vn_dir_entry"  drop constraint if exists "fkryi5xny4gg8sp06uef12ieeq5",
	add constraint "fkryi5xny4gg8sp06uef12ieeq5" foreign key ("parent_id") references "public"."vn_inode" ("id");
	
alter table if exists "public"."vn_inode_path_segment" drop constraint if exists "fka7ehnitijgi0le9m875fxw42v",
	add constraint "fka7ehnitijgi0le9m875fxw42v" foreign key ("dir_entry_id") references "public"."vn_dir_entry" ("id");
	
alter table if exists "public"."vn_inode_path_segment" drop constraint if exists "fkg9to0spyux7e4cyp7fpxq27dj",
	add constraint "fkg9to0spyux7e4cyp7fpxq27dj" foreign key ("inode_id") references "public"."vn_inode" ("id");
	
alter table if exists "public"."vn_node_head"  drop constraint if exists "fkaono5m08t5x8txq0vg3ca3wdh",
	add constraint "fkaono5m08t5x8txq0vg3ca3wdh" foreign key ("inode_id") references "public"."vn_inode" ("id");
	
alter table if exists "public"."vn_node_head" drop constraint if exists "fkod48yv13fhdrs5rxjxmj8u1od", 
	add constraint "fkod48yv13fhdrs5rxjxmj8u1od" foreign key ("version_id") references "public"."vn_node_version" ("id");
	
alter table if exists "public"."vn_node_version" drop constraint if exists "fkgsea7tlnqrybidbrinb952lw0",
	add constraint "fkgsea7tlnqrybidbrinb952lw0" foreign key ("inode_id") references "public"."vn_inode" ("id");
	
alter table if exists "public"."vn_path_lock" drop constraint if exists "vn_path_lock_lock_group_id_fkey",
	add constraint  "vn_path_lock_lock_group_id_fkey" foreign key ("lock_group_id") references "public"."vn_lock_group" ("lock_group_id");

create sequence if not exists "public"."vn_fence_token_seq";
