create schema if not exists "public";
create extension if not exists ltree;

create sequence if not exists "public"."vn_fence_token_seq";
create table if not exists "public"."vn_dir_entry" ("child_id" bigint not null, "created_at" timestamp(6) with time zone not null, "id" bigint not null, "parent_id" bigint not null, "name" varchar(255) not null);
create table if not exists "public"."vn_inode" ("created_at" timestamp(6) with time zone not null, "id" bigint not null, "scope_key" "public"."ltree");
create table if not exists "public"."vn_inode_path_segment" ("ord" integer not null, "created_at" timestamp(6) with time zone not null, "dir_entry_id" bigint not null, "id" bigint not null, "inode_id" bigint not null);
create table if not exists "public"."vn_lock_group" ("lock_group_id" uuid not null, "owner_id" clob not null, "fence_token" bigint, "active" boolean not null default true, "acquired_at" timestamp(6) with time zone not null default now(), "expires_at" timestamp(6) with time zone, "released_at" timestamp(6) with time zone);
create table if not exists "public"."vn_node_head" ("fence_token" bigint, "inode_id" bigint not null, "updated_at" timestamp(6) with time zone not null, "version_id" bigint not null);
create table if not exists "public"."vn_node_version" ("id" bigint not null, "inode_id" bigint not null, "size" bigint not null, "timestamp" bigint not null, "context_name" varchar(255), "correlation_id" varchar(255), "hash" varchar(255), "mime_type" varchar(255), "name" varchar(255), "operation" varchar(255), "path" varchar(255), "principal" varchar(255), "transaction_id" varchar(255), "transaction_result" varchar(255), "workflow_id" varchar(255));
create table if not exists "public"."vn_path_lock" ("id" bigint not null, "lock_group_id" uuid not null, "owner_id" clob not null, "scope_key" "public"."ltree" not null, "active" boolean not null default true, "acquired_at" timestamp(6) with time zone not null default now(), "released_at" timestamp(6) with time zone);
create table if not exists "public"."vn_txn_epoch" ("txn_id" clob not null, "lock_group_id" uuid, "fence_token" bigint, "status" clob not null, "updated_at" timestamp(6) with time zone not null default now());
alter table if exists "public"."vn_dir_entry" drop constraint if exists "vn_dir_entry_pkey", add constraint "vn_dir_entry_pkey" primary key ("id");
alter table if exists "public"."vn_dir_entry" drop constraint if exists "uq_dir_parent_name", add constraint "uq_dir_parent_name" unique ("parent_id", "name");
alter table if exists "public"."vn_dir_entry" drop constraint if exists "vn_dir_entry_child_id_fk", add constraint "vn_dir_entry_child_id_fk" foreign key ("child_id") references "public"."vn_inode" ("id");
alter table if exists "public"."vn_dir_entry" drop constraint if exists "vn_dir_entry_parent_id_fk", add constraint "vn_dir_entry_parent_id_fk" foreign key ("parent_id") references "public"."vn_inode" ("id");
alter table if exists "public"."vn_inode" drop constraint if exists "vn_inode_pkey", add constraint "vn_inode_pkey" primary key ("id");
alter table if exists "public"."vn_inode_path_segment" drop constraint if exists "vn_inode_path_segment_pkey", add constraint "vn_inode_path_segment_pkey" primary key ("id");
alter table if exists "public"."vn_inode_path_segment" drop constraint if exists "uq_inode_ord", add constraint "uq_inode_ord" unique ("inode_id", "ord");
alter table if exists "public"."vn_inode_path_segment" drop constraint if exists "vn_inode_path_segment_dir_entry_id_fk", add constraint "vn_inode_path_segment_dir_entry_id_fk" foreign key ("dir_entry_id") references "public"."vn_dir_entry" ("id");
alter table if exists "public"."vn_inode_path_segment" drop constraint if exists "vn_inode_path_segment_inode_id_fk", add constraint "vn_inode_path_segment_inode_id_fk" foreign key ("inode_id") references "public"."vn_inode" ("id");
alter table if exists "public"."vn_lock_group" drop constraint if exists "vn_lock_group_pkey", add constraint "vn_lock_group_pkey" primary key ("lock_group_id");
alter table if exists "public"."vn_node_head" drop constraint if exists "vn_node_head_pkey", add constraint "vn_node_head_pkey" primary key ("inode_id");
alter table if exists "public"."vn_node_head" drop constraint if exists "vn_node_head_inode_id_fk", add constraint "vn_node_head_inode_id_fk" foreign key ("inode_id") references "public"."vn_inode" ("id");
alter table if exists "public"."vn_node_head" drop constraint if exists "vn_node_head_version_id_fk", add constraint "vn_node_head_version_id_fk" foreign key ("version_id") references "public"."vn_node_version" ("id");
alter table if exists "public"."vn_node_version" drop constraint if exists "vn_node_version_pkey", add constraint "vn_node_version_pkey" primary key ("id");
alter table if exists "public"."vn_node_version" drop constraint if exists "vn_node_version_inode_id_fk", add constraint "vn_node_version_inode_id_fk" foreign key ("inode_id") references "public"."vn_inode" ("id");
alter table if exists "public"."vn_path_lock" drop constraint if exists "vn_path_lock_pkey", add constraint "vn_path_lock_pkey" primary key ("id");
alter table if exists "public"."vn_path_lock" drop constraint if exists "vn_path_lock_lock_group_id_fk", add constraint "vn_path_lock_lock_group_id_fk" foreign key ("lock_group_id") references "public"."vn_lock_group" ("lock_group_id");
alter table if exists "public"."vn_txn_epoch" drop constraint if exists "vn_txn_epoch_pkey", add constraint "vn_txn_epoch_pkey" primary key ("txn_id");
create index if not exists "ix_dir_child" on "public"."vn_dir_entry"();
create index if not exists "ix_dir_parent" on "public"."vn_dir_entry"();
create unique index if not exists "uq_vn_inode_scope_key" on "public"."vn_inode"();
create index if not exists "ix_inode_path_inode" on "public"."vn_inode_path_segment"();
create index if not exists "ix_vn_lock_group_active_expires" on "public"."vn_lock_group"();
create index if not exists "ix_vn_lock_group_owner_active" on "public"."vn_lock_group"();
create index if not exists "ix_ver_inode_timestamp" on "public"."vn_node_version"();
create index if not exists "ix_vn_path_lock_group" on "public"."vn_path_lock"();
create index if not exists "ix_vn_path_lock_owner_active" on "public"."vn_path_lock"();
create index if not exists "ix_vn_path_lock_scope_key_gist" on "public"."vn_path_lock"();
create index if not exists "ix_vn_txn_epoch_status" on "public"."vn_txn_epoch"();
