create schema if not exists "public";
create extension if not exists ltree;

alter table if exists "public"."vn_dir_entry" drop constraint if exists "uq_dir_parent_name";
alter table if exists "public"."vn_dir_entry" drop constraint if exists "vn_dir_entry_pkey";
alter table if exists "public"."vn_dir_entry" drop constraint if exists "vn_dir_entry_child_id_fk";
alter table if exists "public"."vn_dir_entry" drop constraint if exists "vn_dir_entry_parent_id_fk";
alter table if exists "public"."vn_inode" drop constraint if exists "vn_inode_pkey";
alter table if exists "public"."vn_inode_path_segment" drop constraint if exists "uq_inode_ord";
alter table if exists "public"."vn_inode_path_segment" drop constraint if exists "vn_inode_path_segment_pkey";
alter table if exists "public"."vn_inode_path_segment" drop constraint if exists "vn_inode_path_segment_dir_entry_id_fk";
alter table if exists "public"."vn_inode_path_segment" drop constraint if exists "vn_inode_path_segment_inode_id_fk";
alter table if exists "public"."vn_lock_group" drop constraint if exists "vn_lock_group_pkey";
alter table if exists "public"."vn_node_head" drop constraint if exists "vn_node_head_pkey";
alter table if exists "public"."vn_node_head" drop constraint if exists "vn_node_head_inode_id_fk";
alter table if exists "public"."vn_node_head" drop constraint if exists "vn_node_head_version_id_fk";
alter table if exists "public"."vn_node_version" drop constraint if exists "vn_node_version_pkey";
alter table if exists "public"."vn_node_version" drop constraint if exists "vn_node_version_inode_id_fk";
alter table if exists "public"."vn_path_lock" drop constraint if exists "vn_path_lock_pkey";
alter table if exists "public"."vn_path_lock" drop constraint if exists "vn_path_lock_lock_group_id_fk";
alter table if exists "public"."vn_txn_epoch" drop constraint if exists "vn_txn_epoch_pkey";
drop index if exists "ix_dir_child";
drop index if exists "ix_dir_parent";
drop index if exists "ix_inode_path_inode";
drop index if exists "ix_ver_inode_timestamp";
drop index if exists "ix_vn_lock_group_active_expires";
drop index if exists "ix_vn_lock_group_owner_active";
drop index if exists "ix_vn_path_lock_group";
drop index if exists "ix_vn_path_lock_owner_active";
drop index if exists "ix_vn_path_lock_scope_key_gist";
drop index if exists "ix_vn_txn_epoch_status";
drop index if exists "uq_vn_inode_scope_key";
drop table if exists "public"."vn_txn_epoch";
drop table if exists "public"."vn_path_lock";
drop table if exists "public"."vn_node_version";
drop table if exists "public"."vn_node_head";
drop table if exists "public"."vn_lock_group";
drop table if exists "public"."vn_inode_path_segment";
drop table if exists "public"."vn_inode";
drop table if exists "public"."vn_dir_entry";
drop sequence if exists "public"."vn_fence_token_seq";
