/*
 * This file is generated by jOOQ.
 */
package com.veritynow.core.store.persistence.jooq.tables;


import com.veritynow.core.store.persistence.jooq.Keys;
import com.veritynow.core.store.persistence.jooq.Public;
import com.veritynow.core.store.persistence.jooq.tables.records.VnBlobRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VnBlob extends TableImpl<VnBlobRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.vn_blob</code>
     */
    public static final VnBlob VN_BLOB = new VnBlob();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VnBlobRecord> getRecordType() {
        return VnBlobRecord.class;
    }

    /**
     * The column <code>public.vn_blob.hash</code>.
     */
    public final TableField<VnBlobRecord, String> HASH = createField(DSL.name("hash"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.vn_blob.hash_algorithm</code>.
     */
    public final TableField<VnBlobRecord, String> HASH_ALGORITHM = createField(DSL.name("hash_algorithm"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.vn_blob.size</code>.
     */
    public final TableField<VnBlobRecord, Long> SIZE = createField(DSL.name("size"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.vn_blob.mime_type</code>.
     */
    public final TableField<VnBlobRecord, String> MIME_TYPE = createField(DSL.name("mime_type"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.vn_blob.name</code>.
     */
    public final TableField<VnBlobRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255), this, "");

    private VnBlob(Name alias, Table<VnBlobRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VnBlob(Name alias, Table<VnBlobRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.vn_blob</code> table reference
     */
    public VnBlob(String alias) {
        this(DSL.name(alias), VN_BLOB);
    }

    /**
     * Create an aliased <code>public.vn_blob</code> table reference
     */
    public VnBlob(Name alias) {
        this(alias, VN_BLOB);
    }

    /**
     * Create a <code>public.vn_blob</code> table reference
     */
    public VnBlob() {
        this(DSL.name("vn_blob"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<VnBlobRecord> getPrimaryKey() {
        return Keys.VN_BLOB_PKEY;
    }

    @Override
    public VnBlob as(String alias) {
        return new VnBlob(DSL.name(alias), this);
    }

    @Override
    public VnBlob as(Name alias) {
        return new VnBlob(alias, this);
    }

    @Override
    public VnBlob as(Table<?> alias) {
        return new VnBlob(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VnBlob rename(String name) {
        return new VnBlob(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VnBlob rename(Name name) {
        return new VnBlob(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VnBlob rename(Table<?> name) {
        return new VnBlob(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnBlob where(Condition condition) {
        return new VnBlob(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnBlob where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnBlob where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnBlob where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VnBlob where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VnBlob where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VnBlob where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VnBlob where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnBlob whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnBlob whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
