/*
 * This file is generated by jOOQ.
 */
package com.veritynow.core.store.persistence.jooq.tables;


import com.veritynow.core.store.persistence.jooq.Indexes;
import com.veritynow.core.store.persistence.jooq.Keys;
import com.veritynow.core.store.persistence.jooq.Public;
import com.veritynow.core.store.persistence.jooq.tables.VnInode.VnInodePath;
import com.veritynow.core.store.persistence.jooq.tables.VnInodePathSegment.VnInodePathSegmentPath;
import com.veritynow.core.store.persistence.jooq.tables.records.VnDirEntryRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VnDirEntry extends TableImpl<VnDirEntryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.vn_dir_entry</code>
     */
    public static final VnDirEntry VN_DIR_ENTRY = new VnDirEntry();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VnDirEntryRecord> getRecordType() {
        return VnDirEntryRecord.class;
    }

    /**
     * The column <code>public.vn_dir_entry.child_id</code>.
     */
    public final TableField<VnDirEntryRecord, Long> CHILD_ID = createField(DSL.name("child_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.vn_dir_entry.created_at</code>.
     */
    public final TableField<VnDirEntryRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.vn_dir_entry.id</code>.
     */
    public final TableField<VnDirEntryRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.vn_dir_entry.parent_id</code>.
     */
    public final TableField<VnDirEntryRecord, Long> PARENT_ID = createField(DSL.name("parent_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.vn_dir_entry.name</code>.
     */
    public final TableField<VnDirEntryRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private VnDirEntry(Name alias, Table<VnDirEntryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VnDirEntry(Name alias, Table<VnDirEntryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.vn_dir_entry</code> table reference
     */
    public VnDirEntry(String alias) {
        this(DSL.name(alias), VN_DIR_ENTRY);
    }

    /**
     * Create an aliased <code>public.vn_dir_entry</code> table reference
     */
    public VnDirEntry(Name alias) {
        this(alias, VN_DIR_ENTRY);
    }

    /**
     * Create a <code>public.vn_dir_entry</code> table reference
     */
    public VnDirEntry() {
        this(DSL.name("vn_dir_entry"), null);
    }

    public <O extends Record> VnDirEntry(Table<O> path, ForeignKey<O, VnDirEntryRecord> childPath, InverseForeignKey<O, VnDirEntryRecord> parentPath) {
        super(path, childPath, parentPath, VN_DIR_ENTRY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class VnDirEntryPath extends VnDirEntry implements Path<VnDirEntryRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> VnDirEntryPath(Table<O> path, ForeignKey<O, VnDirEntryRecord> childPath, InverseForeignKey<O, VnDirEntryRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private VnDirEntryPath(Name alias, Table<VnDirEntryRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public VnDirEntryPath as(String alias) {
            return new VnDirEntryPath(DSL.name(alias), this);
        }

        @Override
        public VnDirEntryPath as(Name alias) {
            return new VnDirEntryPath(alias, this);
        }

        @Override
        public VnDirEntryPath as(Table<?> alias) {
            return new VnDirEntryPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IX_DIR_CHILD, Indexes.IX_DIR_PARENT);
    }

    @Override
    public Identity<VnDirEntryRecord, Long> getIdentity() {
        return (Identity<VnDirEntryRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<VnDirEntryRecord> getPrimaryKey() {
        return Keys.VN_DIR_ENTRY_PKEY;
    }

    @Override
    public List<UniqueKey<VnDirEntryRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UQ_DIR_PARENT_NAME);
    }

    @Override
    public List<ForeignKey<VnDirEntryRecord, ?>> getReferences() {
        return Arrays.asList(Keys.VN_DIR_ENTRY__VN_DIR_ENTRY_CHILD_ID_FK, Keys.VN_DIR_ENTRY__VN_DIR_ENTRY_PARENT_ID_FK);
    }

    private transient VnInodePath _vnDirEntryChildIdFk;

    /**
     * Get the implicit join path to the <code>public.vn_inode</code> table, via
     * the <code>vn_dir_entry_child_id_fk</code> key.
     */
    public VnInodePath vnDirEntryChildIdFk() {
        if (_vnDirEntryChildIdFk == null)
            _vnDirEntryChildIdFk = new VnInodePath(this, Keys.VN_DIR_ENTRY__VN_DIR_ENTRY_CHILD_ID_FK, null);

        return _vnDirEntryChildIdFk;
    }

    private transient VnInodePath _vnDirEntryParentIdFk;

    /**
     * Get the implicit join path to the <code>public.vn_inode</code> table, via
     * the <code>vn_dir_entry_parent_id_fk</code> key.
     */
    public VnInodePath vnDirEntryParentIdFk() {
        if (_vnDirEntryParentIdFk == null)
            _vnDirEntryParentIdFk = new VnInodePath(this, Keys.VN_DIR_ENTRY__VN_DIR_ENTRY_PARENT_ID_FK, null);

        return _vnDirEntryParentIdFk;
    }

    private transient VnInodePathSegmentPath _vnInodePathSegment;

    /**
     * Get the implicit to-many join path to the
     * <code>public.vn_inode_path_segment</code> table
     */
    public VnInodePathSegmentPath vnInodePathSegment() {
        if (_vnInodePathSegment == null)
            _vnInodePathSegment = new VnInodePathSegmentPath(this, null, Keys.VN_INODE_PATH_SEGMENT__VN_INODE_PATH_SEGMENT_DIR_ENTRY_ID_FK.getInverseKey());

        return _vnInodePathSegment;
    }

    @Override
    public VnDirEntry as(String alias) {
        return new VnDirEntry(DSL.name(alias), this);
    }

    @Override
    public VnDirEntry as(Name alias) {
        return new VnDirEntry(alias, this);
    }

    @Override
    public VnDirEntry as(Table<?> alias) {
        return new VnDirEntry(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VnDirEntry rename(String name) {
        return new VnDirEntry(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VnDirEntry rename(Name name) {
        return new VnDirEntry(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VnDirEntry rename(Table<?> name) {
        return new VnDirEntry(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnDirEntry where(Condition condition) {
        return new VnDirEntry(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnDirEntry where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnDirEntry where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnDirEntry where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VnDirEntry where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VnDirEntry where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VnDirEntry where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VnDirEntry where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnDirEntry whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnDirEntry whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
