/*
 * This file is generated by jOOQ.
 */
package com.veritynow.core.store.persistence.jooq.tables;


import com.veritynow.core.store.persistence.jooq.Indexes;
import com.veritynow.core.store.persistence.jooq.Keys;
import com.veritynow.core.store.persistence.jooq.Public;
import com.veritynow.core.store.persistence.jooq.tables.VnDirEntry.VnDirEntryPath;
import com.veritynow.core.store.persistence.jooq.tables.VnInode.VnInodePath;
import com.veritynow.core.store.persistence.jooq.tables.records.VnInodePathSegmentRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VnInodePathSegment extends TableImpl<VnInodePathSegmentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.vn_inode_path_segment</code>
     */
    public static final VnInodePathSegment VN_INODE_PATH_SEGMENT = new VnInodePathSegment();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VnInodePathSegmentRecord> getRecordType() {
        return VnInodePathSegmentRecord.class;
    }

    /**
     * The column <code>public.vn_inode_path_segment.ord</code>.
     */
    public final TableField<VnInodePathSegmentRecord, Integer> ORD = createField(DSL.name("ord"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.vn_inode_path_segment.created_at</code>.
     */
    public final TableField<VnInodePathSegmentRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.vn_inode_path_segment.dir_entry_id</code>.
     */
    public final TableField<VnInodePathSegmentRecord, Long> DIR_ENTRY_ID = createField(DSL.name("dir_entry_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.vn_inode_path_segment.id</code>.
     */
    public final TableField<VnInodePathSegmentRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.vn_inode_path_segment.inode_id</code>.
     */
    public final TableField<VnInodePathSegmentRecord, Long> INODE_ID = createField(DSL.name("inode_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private VnInodePathSegment(Name alias, Table<VnInodePathSegmentRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VnInodePathSegment(Name alias, Table<VnInodePathSegmentRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.vn_inode_path_segment</code> table
     * reference
     */
    public VnInodePathSegment(String alias) {
        this(DSL.name(alias), VN_INODE_PATH_SEGMENT);
    }

    /**
     * Create an aliased <code>public.vn_inode_path_segment</code> table
     * reference
     */
    public VnInodePathSegment(Name alias) {
        this(alias, VN_INODE_PATH_SEGMENT);
    }

    /**
     * Create a <code>public.vn_inode_path_segment</code> table reference
     */
    public VnInodePathSegment() {
        this(DSL.name("vn_inode_path_segment"), null);
    }

    public <O extends Record> VnInodePathSegment(Table<O> path, ForeignKey<O, VnInodePathSegmentRecord> childPath, InverseForeignKey<O, VnInodePathSegmentRecord> parentPath) {
        super(path, childPath, parentPath, VN_INODE_PATH_SEGMENT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class VnInodePathSegmentPath extends VnInodePathSegment implements Path<VnInodePathSegmentRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> VnInodePathSegmentPath(Table<O> path, ForeignKey<O, VnInodePathSegmentRecord> childPath, InverseForeignKey<O, VnInodePathSegmentRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private VnInodePathSegmentPath(Name alias, Table<VnInodePathSegmentRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public VnInodePathSegmentPath as(String alias) {
            return new VnInodePathSegmentPath(DSL.name(alias), this);
        }

        @Override
        public VnInodePathSegmentPath as(Name alias) {
            return new VnInodePathSegmentPath(alias, this);
        }

        @Override
        public VnInodePathSegmentPath as(Table<?> alias) {
            return new VnInodePathSegmentPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IX_INODE_PATH_DIR_ENTRY, Indexes.IX_INODE_PATH_INODE);
    }

    @Override
    public Identity<VnInodePathSegmentRecord, Long> getIdentity() {
        return (Identity<VnInodePathSegmentRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<VnInodePathSegmentRecord> getPrimaryKey() {
        return Keys.VN_INODE_PATH_SEGMENT_PKEY;
    }

    @Override
    public List<UniqueKey<VnInodePathSegmentRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UQ_INODE_ORD);
    }

    @Override
    public List<ForeignKey<VnInodePathSegmentRecord, ?>> getReferences() {
        return Arrays.asList(Keys.VN_INODE_PATH_SEGMENT__VN_INODE_PATH_SEGMENT_DIR_ENTRY_ID_FK, Keys.VN_INODE_PATH_SEGMENT__VN_INODE_PATH_SEGMENT_INODE_ID_FK);
    }

    private transient VnDirEntryPath _vnDirEntry;

    /**
     * Get the implicit join path to the <code>public.vn_dir_entry</code> table.
     */
    public VnDirEntryPath vnDirEntry() {
        if (_vnDirEntry == null)
            _vnDirEntry = new VnDirEntryPath(this, Keys.VN_INODE_PATH_SEGMENT__VN_INODE_PATH_SEGMENT_DIR_ENTRY_ID_FK, null);

        return _vnDirEntry;
    }

    private transient VnInodePath _vnInode;

    /**
     * Get the implicit join path to the <code>public.vn_inode</code> table.
     */
    public VnInodePath vnInode() {
        if (_vnInode == null)
            _vnInode = new VnInodePath(this, Keys.VN_INODE_PATH_SEGMENT__VN_INODE_PATH_SEGMENT_INODE_ID_FK, null);

        return _vnInode;
    }

    @Override
    public VnInodePathSegment as(String alias) {
        return new VnInodePathSegment(DSL.name(alias), this);
    }

    @Override
    public VnInodePathSegment as(Name alias) {
        return new VnInodePathSegment(alias, this);
    }

    @Override
    public VnInodePathSegment as(Table<?> alias) {
        return new VnInodePathSegment(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VnInodePathSegment rename(String name) {
        return new VnInodePathSegment(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VnInodePathSegment rename(Name name) {
        return new VnInodePathSegment(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VnInodePathSegment rename(Table<?> name) {
        return new VnInodePathSegment(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnInodePathSegment where(Condition condition) {
        return new VnInodePathSegment(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnInodePathSegment where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnInodePathSegment where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnInodePathSegment where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VnInodePathSegment where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VnInodePathSegment where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VnInodePathSegment where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VnInodePathSegment where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnInodePathSegment whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnInodePathSegment whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
