/*
 * This file is generated by jOOQ.
 */
package com.veritynow.core.store.persistence.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.DefaultDataType;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import com.veritynow.core.store.db.jooq.binding.LTree;
import com.veritynow.core.store.db.jooq.binding.LTreeBinding;
import com.veritynow.core.store.persistence.jooq.Indexes;
import com.veritynow.core.store.persistence.jooq.Keys;
import com.veritynow.core.store.persistence.jooq.Public;
import com.veritynow.core.store.persistence.jooq.tables.VnDirEntry.VnDirEntryPath;
import com.veritynow.core.store.persistence.jooq.tables.VnInodePathSegment.VnInodePathSegmentPath;
import com.veritynow.core.store.persistence.jooq.tables.VnNodeHead.VnNodeHeadPath;
import com.veritynow.core.store.persistence.jooq.tables.VnNodeVersion.VnNodeVersionPath;
import com.veritynow.core.store.persistence.jooq.tables.records.VnInodeRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VnInode extends TableImpl<VnInodeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.vn_inode</code>
     */
    public static final VnInode VN_INODE = new VnInode();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VnInodeRecord> getRecordType() {
        return VnInodeRecord.class;
    }

    /**
     * The column <code>public.vn_inode.created_at</code>.
     */
    public final TableField<VnInodeRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.vn_inode.id</code>.
     */
    public final TableField<VnInodeRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.vn_inode.scope_key</code>.
     */
    public final TableField<VnInodeRecord, LTree> SCOPE_KEY = createField(DSL.name("scope_key"), DefaultDataType.getDefaultDataType("\"public\".\"ltree\""), this, "", new LTreeBinding());

    private VnInode(Name alias, Table<VnInodeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VnInode(Name alias, Table<VnInodeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.vn_inode</code> table reference
     */
    public VnInode(String alias) {
        this(DSL.name(alias), VN_INODE);
    }

    /**
     * Create an aliased <code>public.vn_inode</code> table reference
     */
    public VnInode(Name alias) {
        this(alias, VN_INODE);
    }

    /**
     * Create a <code>public.vn_inode</code> table reference
     */
    public VnInode() {
        this(DSL.name("vn_inode"), null);
    }

    public <O extends Record> VnInode(Table<O> path, ForeignKey<O, VnInodeRecord> childPath, InverseForeignKey<O, VnInodeRecord> parentPath) {
        super(path, childPath, parentPath, VN_INODE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class VnInodePath extends VnInode implements Path<VnInodeRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> VnInodePath(Table<O> path, ForeignKey<O, VnInodeRecord> childPath, InverseForeignKey<O, VnInodeRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private VnInodePath(Name alias, Table<VnInodeRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public VnInodePath as(String alias) {
            return new VnInodePath(DSL.name(alias), this);
        }

        @Override
        public VnInodePath as(Name alias) {
            return new VnInodePath(alias, this);
        }

        @Override
        public VnInodePath as(Table<?> alias) {
            return new VnInodePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.UQ_VN_INODE_SCOPE_KEY);
    }

    @Override
    public Identity<VnInodeRecord, Long> getIdentity() {
        return (Identity<VnInodeRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<VnInodeRecord> getPrimaryKey() {
        return Keys.VN_INODE_PKEY;
    }

    private transient VnNodeHeadPath _vnNodeHead;

    /**
     * Get the implicit to-many join path to the
     * <code>public.vn_node_head</code> table
     */
    public VnNodeHeadPath vnNodeHead() {
        if (_vnNodeHead == null)
            _vnNodeHead = new VnNodeHeadPath(this, null, Keys.VN_NODE_HEAD__FKAONO5M08T5X8TXQ0VG3CA3WDH.getInverseKey());

        return _vnNodeHead;
    }

    private transient VnInodePathSegmentPath _vnInodePathSegment;

    /**
     * Get the implicit to-many join path to the
     * <code>public.vn_inode_path_segment</code> table
     */
    public VnInodePathSegmentPath vnInodePathSegment() {
        if (_vnInodePathSegment == null)
            _vnInodePathSegment = new VnInodePathSegmentPath(this, null, Keys.VN_INODE_PATH_SEGMENT__FKG9TO0SPYUX7E4CYP7FPXQ27DJ.getInverseKey());

        return _vnInodePathSegment;
    }

    private transient VnNodeVersionPath _vnNodeVersion;

    /**
     * Get the implicit to-many join path to the
     * <code>public.vn_node_version</code> table
     */
    public VnNodeVersionPath vnNodeVersion() {
        if (_vnNodeVersion == null)
            _vnNodeVersion = new VnNodeVersionPath(this, null, Keys.VN_NODE_VERSION__FKGSEA7TLNQRYBIDBRINB952LW0.getInverseKey());

        return _vnNodeVersion;
    }

    private transient VnDirEntryPath _fkphtn4icdtoh8xgjuvtw4qcd0i;

    /**
     * Get the implicit to-many join path to the
     * <code>public.vn_dir_entry</code> table, via the
     * <code>fkphtn4icdtoh8xgjuvtw4qcd0i</code> key
     */
    public VnDirEntryPath fkphtn4icdtoh8xgjuvtw4qcd0i() {
        if (_fkphtn4icdtoh8xgjuvtw4qcd0i == null)
            _fkphtn4icdtoh8xgjuvtw4qcd0i = new VnDirEntryPath(this, null, Keys.VN_DIR_ENTRY__FKPHTN4ICDTOH8XGJUVTW4QCD0I.getInverseKey());

        return _fkphtn4icdtoh8xgjuvtw4qcd0i;
    }

    private transient VnDirEntryPath _fkryi5xny4gg8sp06uef12ieeq5;

    /**
     * Get the implicit to-many join path to the
     * <code>public.vn_dir_entry</code> table, via the
     * <code>fkryi5xny4gg8sp06uef12ieeq5</code> key
     */
    public VnDirEntryPath fkryi5xny4gg8sp06uef12ieeq5() {
        if (_fkryi5xny4gg8sp06uef12ieeq5 == null)
            _fkryi5xny4gg8sp06uef12ieeq5 = new VnDirEntryPath(this, null, Keys.VN_DIR_ENTRY__FKRYI5XNY4GG8SP06UEF12IEEQ5.getInverseKey());

        return _fkryi5xny4gg8sp06uef12ieeq5;
    }

    @Override
    public VnInode as(String alias) {
        return new VnInode(DSL.name(alias), this);
    }

    @Override
    public VnInode as(Name alias) {
        return new VnInode(alias, this);
    }

    @Override
    public VnInode as(Table<?> alias) {
        return new VnInode(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VnInode rename(String name) {
        return new VnInode(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VnInode rename(Name name) {
        return new VnInode(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VnInode rename(Table<?> name) {
        return new VnInode(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnInode where(Condition condition) {
        return new VnInode(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnInode where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnInode where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnInode where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VnInode where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VnInode where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VnInode where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VnInode where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnInode whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnInode whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
