/*
 * This file is generated by jOOQ.
 */
package com.veritynow.core.store.persistence.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import com.veritynow.core.store.persistence.jooq.Indexes;
import com.veritynow.core.store.persistence.jooq.Keys;
import com.veritynow.core.store.persistence.jooq.Public;
import com.veritynow.core.store.persistence.jooq.tables.VnPathLock.VnPathLockPath;
import com.veritynow.core.store.persistence.jooq.tables.records.VnLockGroupRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VnLockGroup extends TableImpl<VnLockGroupRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.vn_lock_group</code>
     */
    public static final VnLockGroup VN_LOCK_GROUP = new VnLockGroup();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VnLockGroupRecord> getRecordType() {
        return VnLockGroupRecord.class;
    }

    /**
     * The column <code>public.vn_lock_group.lock_group_id</code>.
     */
    public final TableField<VnLockGroupRecord, UUID> LOCK_GROUP_ID = createField(DSL.name("lock_group_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.vn_lock_group.owner_id</code>.
     */
    public final TableField<VnLockGroupRecord, String> OWNER_ID = createField(DSL.name("owner_id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.vn_lock_group.fence_token</code>.
     */
    public final TableField<VnLockGroupRecord, Long> FENCE_TOKEN = createField(DSL.name("fence_token"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.vn_lock_group.active</code>.
     */
    public final TableField<VnLockGroupRecord, Boolean> ACTIVE = createField(DSL.name("active"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.vn_lock_group.acquired_at</code>.
     */
    public final TableField<VnLockGroupRecord, OffsetDateTime> ACQUIRED_AT = createField(DSL.name("acquired_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.vn_lock_group.expires_at</code>.
     */
    public final TableField<VnLockGroupRecord, OffsetDateTime> EXPIRES_AT = createField(DSL.name("expires_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.vn_lock_group.released_at</code>.
     */
    public final TableField<VnLockGroupRecord, OffsetDateTime> RELEASED_AT = createField(DSL.name("released_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private VnLockGroup(Name alias, Table<VnLockGroupRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VnLockGroup(Name alias, Table<VnLockGroupRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.vn_lock_group</code> table reference
     */
    public VnLockGroup(String alias) {
        this(DSL.name(alias), VN_LOCK_GROUP);
    }

    /**
     * Create an aliased <code>public.vn_lock_group</code> table reference
     */
    public VnLockGroup(Name alias) {
        this(alias, VN_LOCK_GROUP);
    }

    /**
     * Create a <code>public.vn_lock_group</code> table reference
     */
    public VnLockGroup() {
        this(DSL.name("vn_lock_group"), null);
    }

    public <O extends Record> VnLockGroup(Table<O> path, ForeignKey<O, VnLockGroupRecord> childPath, InverseForeignKey<O, VnLockGroupRecord> parentPath) {
        super(path, childPath, parentPath, VN_LOCK_GROUP);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class VnLockGroupPath extends VnLockGroup implements Path<VnLockGroupRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> VnLockGroupPath(Table<O> path, ForeignKey<O, VnLockGroupRecord> childPath, InverseForeignKey<O, VnLockGroupRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private VnLockGroupPath(Name alias, Table<VnLockGroupRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public VnLockGroupPath as(String alias) {
            return new VnLockGroupPath(DSL.name(alias), this);
        }

        @Override
        public VnLockGroupPath as(Name alias) {
            return new VnLockGroupPath(alias, this);
        }

        @Override
        public VnLockGroupPath as(Table<?> alias) {
            return new VnLockGroupPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IX_VN_LOCK_GROUP_ACTIVE_EXPIRES, Indexes.IX_VN_LOCK_GROUP_OWNER_ACTIVE);
    }

    @Override
    public UniqueKey<VnLockGroupRecord> getPrimaryKey() {
        return Keys.VN_LOCK_GROUP_PKEY;
    }

    private transient VnPathLockPath _vnPathLock;

    /**
     * Get the implicit to-many join path to the
     * <code>public.vn_path_lock</code> table
     */
    public VnPathLockPath vnPathLock() {
        if (_vnPathLock == null)
            _vnPathLock = new VnPathLockPath(this, null, Keys.VN_PATH_LOCK__VN_PATH_LOCK_LOCK_GROUP_ID_FKEY.getInverseKey());

        return _vnPathLock;
    }

    @Override
    public VnLockGroup as(String alias) {
        return new VnLockGroup(DSL.name(alias), this);
    }

    @Override
    public VnLockGroup as(Name alias) {
        return new VnLockGroup(alias, this);
    }

    @Override
    public VnLockGroup as(Table<?> alias) {
        return new VnLockGroup(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VnLockGroup rename(String name) {
        return new VnLockGroup(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VnLockGroup rename(Name name) {
        return new VnLockGroup(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VnLockGroup rename(Table<?> name) {
        return new VnLockGroup(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnLockGroup where(Condition condition) {
        return new VnLockGroup(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnLockGroup where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnLockGroup where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnLockGroup where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VnLockGroup where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VnLockGroup where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VnLockGroup where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VnLockGroup where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnLockGroup whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnLockGroup whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
