/*
 * This file is generated by jOOQ.
 */
package com.veritynow.core.store.persistence.jooq.tables;


import com.veritynow.core.store.persistence.jooq.Keys;
import com.veritynow.core.store.persistence.jooq.Public;
import com.veritynow.core.store.persistence.jooq.tables.VnInode.VnInodePath;
import com.veritynow.core.store.persistence.jooq.tables.VnNodeVersion.VnNodeVersionPath;
import com.veritynow.core.store.persistence.jooq.tables.records.VnNodeHeadRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VnNodeHead extends TableImpl<VnNodeHeadRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.vn_node_head</code>
     */
    public static final VnNodeHead VN_NODE_HEAD = new VnNodeHead();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VnNodeHeadRecord> getRecordType() {
        return VnNodeHeadRecord.class;
    }

    /**
     * The column <code>public.vn_node_head.fence_token</code>.
     */
    public final TableField<VnNodeHeadRecord, Long> FENCE_TOKEN = createField(DSL.name("fence_token"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.vn_node_head.inode_id</code>.
     */
    public final TableField<VnNodeHeadRecord, Long> INODE_ID = createField(DSL.name("inode_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.vn_node_head.updated_at</code>.
     */
    public final TableField<VnNodeHeadRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.vn_node_head.version_id</code>.
     */
    public final TableField<VnNodeHeadRecord, Long> VERSION_ID = createField(DSL.name("version_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private VnNodeHead(Name alias, Table<VnNodeHeadRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VnNodeHead(Name alias, Table<VnNodeHeadRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.vn_node_head</code> table reference
     */
    public VnNodeHead(String alias) {
        this(DSL.name(alias), VN_NODE_HEAD);
    }

    /**
     * Create an aliased <code>public.vn_node_head</code> table reference
     */
    public VnNodeHead(Name alias) {
        this(alias, VN_NODE_HEAD);
    }

    /**
     * Create a <code>public.vn_node_head</code> table reference
     */
    public VnNodeHead() {
        this(DSL.name("vn_node_head"), null);
    }

    public <O extends Record> VnNodeHead(Table<O> path, ForeignKey<O, VnNodeHeadRecord> childPath, InverseForeignKey<O, VnNodeHeadRecord> parentPath) {
        super(path, childPath, parentPath, VN_NODE_HEAD);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class VnNodeHeadPath extends VnNodeHead implements Path<VnNodeHeadRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> VnNodeHeadPath(Table<O> path, ForeignKey<O, VnNodeHeadRecord> childPath, InverseForeignKey<O, VnNodeHeadRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private VnNodeHeadPath(Name alias, Table<VnNodeHeadRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public VnNodeHeadPath as(String alias) {
            return new VnNodeHeadPath(DSL.name(alias), this);
        }

        @Override
        public VnNodeHeadPath as(Name alias) {
            return new VnNodeHeadPath(alias, this);
        }

        @Override
        public VnNodeHeadPath as(Table<?> alias) {
            return new VnNodeHeadPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<VnNodeHeadRecord> getPrimaryKey() {
        return Keys.VN_NODE_HEAD_PKEY;
    }

    @Override
    public List<ForeignKey<VnNodeHeadRecord, ?>> getReferences() {
        return Arrays.asList(Keys.VN_NODE_HEAD__VN_NODE_HEAD_INODE_ID_FK, Keys.VN_NODE_HEAD__VN_NODE_HEAD_VERSION_ID_FK);
    }

    private transient VnInodePath _vnInode;

    /**
     * Get the implicit join path to the <code>public.vn_inode</code> table.
     */
    public VnInodePath vnInode() {
        if (_vnInode == null)
            _vnInode = new VnInodePath(this, Keys.VN_NODE_HEAD__VN_NODE_HEAD_INODE_ID_FK, null);

        return _vnInode;
    }

    private transient VnNodeVersionPath _vnNodeVersion;

    /**
     * Get the implicit join path to the <code>public.vn_node_version</code>
     * table.
     */
    public VnNodeVersionPath vnNodeVersion() {
        if (_vnNodeVersion == null)
            _vnNodeVersion = new VnNodeVersionPath(this, Keys.VN_NODE_HEAD__VN_NODE_HEAD_VERSION_ID_FK, null);

        return _vnNodeVersion;
    }

    @Override
    public VnNodeHead as(String alias) {
        return new VnNodeHead(DSL.name(alias), this);
    }

    @Override
    public VnNodeHead as(Name alias) {
        return new VnNodeHead(alias, this);
    }

    @Override
    public VnNodeHead as(Table<?> alias) {
        return new VnNodeHead(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VnNodeHead rename(String name) {
        return new VnNodeHead(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VnNodeHead rename(Name name) {
        return new VnNodeHead(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VnNodeHead rename(Table<?> name) {
        return new VnNodeHead(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnNodeHead where(Condition condition) {
        return new VnNodeHead(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnNodeHead where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnNodeHead where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnNodeHead where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VnNodeHead where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VnNodeHead where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VnNodeHead where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VnNodeHead where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnNodeHead whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnNodeHead whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
