/*
 * This file is generated by jOOQ.
 */
package com.veritynow.core.store.persistence.jooq.tables;


import com.veritynow.core.store.persistence.jooq.Indexes;
import com.veritynow.core.store.persistence.jooq.Keys;
import com.veritynow.core.store.persistence.jooq.Public;
import com.veritynow.core.store.persistence.jooq.tables.VnInode.VnInodePath;
import com.veritynow.core.store.persistence.jooq.tables.VnNodeHead.VnNodeHeadPath;
import com.veritynow.core.store.persistence.jooq.tables.records.VnNodeVersionRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VnNodeVersion extends TableImpl<VnNodeVersionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.vn_node_version</code>
     */
    public static final VnNodeVersion VN_NODE_VERSION = new VnNodeVersion();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VnNodeVersionRecord> getRecordType() {
        return VnNodeVersionRecord.class;
    }

    /**
     * The column <code>public.vn_node_version.id</code>.
     */
    public final TableField<VnNodeVersionRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.vn_node_version.inode_id</code>.
     */
    public final TableField<VnNodeVersionRecord, Long> INODE_ID = createField(DSL.name("inode_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.vn_node_version.size</code>.
     */
    public final TableField<VnNodeVersionRecord, Long> SIZE = createField(DSL.name("size"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.vn_node_version.timestamp</code>.
     */
    public final TableField<VnNodeVersionRecord, Long> TIMESTAMP = createField(DSL.name("timestamp"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.vn_node_version.context_name</code>.
     */
    public final TableField<VnNodeVersionRecord, String> CONTEXT_NAME = createField(DSL.name("context_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.vn_node_version.correlation_id</code>.
     */
    public final TableField<VnNodeVersionRecord, String> CORRELATION_ID = createField(DSL.name("correlation_id"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.vn_node_version.hash</code>.
     */
    public final TableField<VnNodeVersionRecord, String> HASH = createField(DSL.name("hash"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.vn_node_version.mime_type</code>.
     */
    public final TableField<VnNodeVersionRecord, String> MIME_TYPE = createField(DSL.name("mime_type"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.vn_node_version.name</code>.
     */
    public final TableField<VnNodeVersionRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.vn_node_version.operation</code>.
     */
    public final TableField<VnNodeVersionRecord, String> OPERATION = createField(DSL.name("operation"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.vn_node_version.path</code>.
     */
    public final TableField<VnNodeVersionRecord, String> PATH = createField(DSL.name("path"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.vn_node_version.principal</code>.
     */
    public final TableField<VnNodeVersionRecord, String> PRINCIPAL = createField(DSL.name("principal"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.vn_node_version.transaction_id</code>.
     */
    public final TableField<VnNodeVersionRecord, String> TRANSACTION_ID = createField(DSL.name("transaction_id"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.vn_node_version.transaction_result</code>.
     */
    public final TableField<VnNodeVersionRecord, String> TRANSACTION_RESULT = createField(DSL.name("transaction_result"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.vn_node_version.workflow_id</code>.
     */
    public final TableField<VnNodeVersionRecord, String> WORKFLOW_ID = createField(DSL.name("workflow_id"), SQLDataType.VARCHAR(255), this, "");

    private VnNodeVersion(Name alias, Table<VnNodeVersionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VnNodeVersion(Name alias, Table<VnNodeVersionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.vn_node_version</code> table reference
     */
    public VnNodeVersion(String alias) {
        this(DSL.name(alias), VN_NODE_VERSION);
    }

    /**
     * Create an aliased <code>public.vn_node_version</code> table reference
     */
    public VnNodeVersion(Name alias) {
        this(alias, VN_NODE_VERSION);
    }

    /**
     * Create a <code>public.vn_node_version</code> table reference
     */
    public VnNodeVersion() {
        this(DSL.name("vn_node_version"), null);
    }

    public <O extends Record> VnNodeVersion(Table<O> path, ForeignKey<O, VnNodeVersionRecord> childPath, InverseForeignKey<O, VnNodeVersionRecord> parentPath) {
        super(path, childPath, parentPath, VN_NODE_VERSION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class VnNodeVersionPath extends VnNodeVersion implements Path<VnNodeVersionRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> VnNodeVersionPath(Table<O> path, ForeignKey<O, VnNodeVersionRecord> childPath, InverseForeignKey<O, VnNodeVersionRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private VnNodeVersionPath(Name alias, Table<VnNodeVersionRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public VnNodeVersionPath as(String alias) {
            return new VnNodeVersionPath(DSL.name(alias), this);
        }

        @Override
        public VnNodeVersionPath as(Name alias) {
            return new VnNodeVersionPath(alias, this);
        }

        @Override
        public VnNodeVersionPath as(Table<?> alias) {
            return new VnNodeVersionPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IX_VER_INODE_TIMESTAMP);
    }

    @Override
    public Identity<VnNodeVersionRecord, Long> getIdentity() {
        return (Identity<VnNodeVersionRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<VnNodeVersionRecord> getPrimaryKey() {
        return Keys.VN_NODE_VERSION_PKEY;
    }

    @Override
    public List<ForeignKey<VnNodeVersionRecord, ?>> getReferences() {
        return Arrays.asList(Keys.VN_NODE_VERSION__FKGSEA7TLNQRYBIDBRINB952LW0);
    }

    private transient VnInodePath _vnInode;

    /**
     * Get the implicit join path to the <code>public.vn_inode</code> table.
     */
    public VnInodePath vnInode() {
        if (_vnInode == null)
            _vnInode = new VnInodePath(this, Keys.VN_NODE_VERSION__FKGSEA7TLNQRYBIDBRINB952LW0, null);

        return _vnInode;
    }

    private transient VnNodeHeadPath _vnNodeHead;

    /**
     * Get the implicit to-many join path to the
     * <code>public.vn_node_head</code> table
     */
    public VnNodeHeadPath vnNodeHead() {
        if (_vnNodeHead == null)
            _vnNodeHead = new VnNodeHeadPath(this, null, Keys.VN_NODE_HEAD__FKOD48YV13FHDRS5RXJXMJ8U1OD.getInverseKey());

        return _vnNodeHead;
    }

    @Override
    public VnNodeVersion as(String alias) {
        return new VnNodeVersion(DSL.name(alias), this);
    }

    @Override
    public VnNodeVersion as(Name alias) {
        return new VnNodeVersion(alias, this);
    }

    @Override
    public VnNodeVersion as(Table<?> alias) {
        return new VnNodeVersion(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VnNodeVersion rename(String name) {
        return new VnNodeVersion(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VnNodeVersion rename(Name name) {
        return new VnNodeVersion(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VnNodeVersion rename(Table<?> name) {
        return new VnNodeVersion(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnNodeVersion where(Condition condition) {
        return new VnNodeVersion(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnNodeVersion where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnNodeVersion where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnNodeVersion where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VnNodeVersion where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VnNodeVersion where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VnNodeVersion where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VnNodeVersion where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnNodeVersion whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnNodeVersion whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
