/*
 * This file is generated by jOOQ.
 */
package com.veritynow.core.store.persistence.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.DefaultDataType;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import com.veritynow.core.store.db.jooq.binding.LTree;
import com.veritynow.core.store.db.jooq.binding.LTreeBinding;
import com.veritynow.core.store.persistence.jooq.Indexes;
import com.veritynow.core.store.persistence.jooq.Keys;
import com.veritynow.core.store.persistence.jooq.Public;
import com.veritynow.core.store.persistence.jooq.tables.VnLockGroup.VnLockGroupPath;
import com.veritynow.core.store.persistence.jooq.tables.records.VnPathLockRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VnPathLock extends TableImpl<VnPathLockRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.vn_path_lock</code>
     */
    public static final VnPathLock VN_PATH_LOCK = new VnPathLock();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VnPathLockRecord> getRecordType() {
        return VnPathLockRecord.class;
    }

    /**
     * The column <code>public.vn_path_lock.id</code>.
     */
    public final TableField<VnPathLockRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.vn_path_lock.lock_group_id</code>.
     */
    public final TableField<VnPathLockRecord, UUID> LOCK_GROUP_ID = createField(DSL.name("lock_group_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.vn_path_lock.owner_id</code>.
     */
    public final TableField<VnPathLockRecord, String> OWNER_ID = createField(DSL.name("owner_id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.vn_path_lock.scope_key</code>.
     */
    public final TableField<VnPathLockRecord, LTree> SCOPE_KEY = createField(DSL.name("scope_key"), DefaultDataType.getDefaultDataType("\"public\".\"ltree\"").nullable(false), this, "", new LTreeBinding());

    /**
     * The column <code>public.vn_path_lock.active</code>.
     */
    public final TableField<VnPathLockRecord, Boolean> ACTIVE = createField(DSL.name("active"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.vn_path_lock.acquired_at</code>.
     */
    public final TableField<VnPathLockRecord, OffsetDateTime> ACQUIRED_AT = createField(DSL.name("acquired_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.vn_path_lock.released_at</code>.
     */
    public final TableField<VnPathLockRecord, OffsetDateTime> RELEASED_AT = createField(DSL.name("released_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private VnPathLock(Name alias, Table<VnPathLockRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VnPathLock(Name alias, Table<VnPathLockRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.vn_path_lock</code> table reference
     */
    public VnPathLock(String alias) {
        this(DSL.name(alias), VN_PATH_LOCK);
    }

    /**
     * Create an aliased <code>public.vn_path_lock</code> table reference
     */
    public VnPathLock(Name alias) {
        this(alias, VN_PATH_LOCK);
    }

    /**
     * Create a <code>public.vn_path_lock</code> table reference
     */
    public VnPathLock() {
        this(DSL.name("vn_path_lock"), null);
    }

    public <O extends Record> VnPathLock(Table<O> path, ForeignKey<O, VnPathLockRecord> childPath, InverseForeignKey<O, VnPathLockRecord> parentPath) {
        super(path, childPath, parentPath, VN_PATH_LOCK);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class VnPathLockPath extends VnPathLock implements Path<VnPathLockRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> VnPathLockPath(Table<O> path, ForeignKey<O, VnPathLockRecord> childPath, InverseForeignKey<O, VnPathLockRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private VnPathLockPath(Name alias, Table<VnPathLockRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public VnPathLockPath as(String alias) {
            return new VnPathLockPath(DSL.name(alias), this);
        }

        @Override
        public VnPathLockPath as(Name alias) {
            return new VnPathLockPath(alias, this);
        }

        @Override
        public VnPathLockPath as(Table<?> alias) {
            return new VnPathLockPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IX_VN_PATH_LOCK_GROUP, Indexes.IX_VN_PATH_LOCK_OWNER_ACTIVE, Indexes.IX_VN_PATH_LOCK_SCOPE_KEY_GIST);
    }

    @Override
    public Identity<VnPathLockRecord, Long> getIdentity() {
        return (Identity<VnPathLockRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<VnPathLockRecord> getPrimaryKey() {
        return Keys.VN_PATH_LOCK_PKEY;
    }

    @Override
    public List<ForeignKey<VnPathLockRecord, ?>> getReferences() {
        return Arrays.asList(Keys.VN_PATH_LOCK__VN_PATH_LOCK_LOCK_GROUP_ID_FKEY);
    }

    private transient VnLockGroupPath _vnLockGroup;

    /**
     * Get the implicit join path to the <code>public.vn_lock_group</code>
     * table.
     */
    public VnLockGroupPath vnLockGroup() {
        if (_vnLockGroup == null)
            _vnLockGroup = new VnLockGroupPath(this, Keys.VN_PATH_LOCK__VN_PATH_LOCK_LOCK_GROUP_ID_FKEY, null);

        return _vnLockGroup;
    }

    @Override
    public VnPathLock as(String alias) {
        return new VnPathLock(DSL.name(alias), this);
    }

    @Override
    public VnPathLock as(Name alias) {
        return new VnPathLock(alias, this);
    }

    @Override
    public VnPathLock as(Table<?> alias) {
        return new VnPathLock(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VnPathLock rename(String name) {
        return new VnPathLock(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VnPathLock rename(Name name) {
        return new VnPathLock(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VnPathLock rename(Table<?> name) {
        return new VnPathLock(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnPathLock where(Condition condition) {
        return new VnPathLock(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnPathLock where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnPathLock where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnPathLock where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VnPathLock where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VnPathLock where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VnPathLock where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VnPathLock where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnPathLock whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnPathLock whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
