/*
 * This file is generated by jOOQ.
 */
package com.veritynow.core.store.persistence.jooq.tables;


import com.veritynow.core.store.persistence.jooq.Indexes;
import com.veritynow.core.store.persistence.jooq.Keys;
import com.veritynow.core.store.persistence.jooq.Public;
import com.veritynow.core.store.persistence.jooq.tables.records.VnTxnEpochRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VnTxnEpoch extends TableImpl<VnTxnEpochRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.vn_txn_epoch</code>
     */
    public static final VnTxnEpoch VN_TXN_EPOCH = new VnTxnEpoch();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VnTxnEpochRecord> getRecordType() {
        return VnTxnEpochRecord.class;
    }

    /**
     * The column <code>public.vn_txn_epoch.txn_id</code>.
     */
    public final TableField<VnTxnEpochRecord, String> TXN_ID = createField(DSL.name("txn_id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.vn_txn_epoch.lock_group_id</code>.
     */
    public final TableField<VnTxnEpochRecord, UUID> LOCK_GROUP_ID = createField(DSL.name("lock_group_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.vn_txn_epoch.fence_token</code>.
     */
    public final TableField<VnTxnEpochRecord, Long> FENCE_TOKEN = createField(DSL.name("fence_token"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.vn_txn_epoch.status</code>.
     */
    public final TableField<VnTxnEpochRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.vn_txn_epoch.updated_at</code>.
     */
    public final TableField<VnTxnEpochRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private VnTxnEpoch(Name alias, Table<VnTxnEpochRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VnTxnEpoch(Name alias, Table<VnTxnEpochRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.vn_txn_epoch</code> table reference
     */
    public VnTxnEpoch(String alias) {
        this(DSL.name(alias), VN_TXN_EPOCH);
    }

    /**
     * Create an aliased <code>public.vn_txn_epoch</code> table reference
     */
    public VnTxnEpoch(Name alias) {
        this(alias, VN_TXN_EPOCH);
    }

    /**
     * Create a <code>public.vn_txn_epoch</code> table reference
     */
    public VnTxnEpoch() {
        this(DSL.name("vn_txn_epoch"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IX_VN_TXN_EPOCH_LOCK_GROUP, Indexes.IX_VN_TXN_EPOCH_STATUS);
    }

    @Override
    public UniqueKey<VnTxnEpochRecord> getPrimaryKey() {
        return Keys.VN_TXN_EPOCH_PKEY;
    }

    @Override
    public VnTxnEpoch as(String alias) {
        return new VnTxnEpoch(DSL.name(alias), this);
    }

    @Override
    public VnTxnEpoch as(Name alias) {
        return new VnTxnEpoch(alias, this);
    }

    @Override
    public VnTxnEpoch as(Table<?> alias) {
        return new VnTxnEpoch(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VnTxnEpoch rename(String name) {
        return new VnTxnEpoch(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VnTxnEpoch rename(Name name) {
        return new VnTxnEpoch(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VnTxnEpoch rename(Table<?> name) {
        return new VnTxnEpoch(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnTxnEpoch where(Condition condition) {
        return new VnTxnEpoch(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnTxnEpoch where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnTxnEpoch where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnTxnEpoch where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VnTxnEpoch where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VnTxnEpoch where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VnTxnEpoch where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VnTxnEpoch where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnTxnEpoch whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VnTxnEpoch whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
